### ISSUE TITLE
[Bug]: nomad [nodeserver - 141:NodeUnpublishVolume]

### ISSUE THREAD

**Issue by cr0c0dylus** [kadalu/kadalu#1004]
kadalu csi plugin docker logs is full of these errors:

[2023-06-16 10:39:25,517] DEBUG [nodeserver - 141:NodeUnpublishVolume] - Received the unmount request    volume=app-prod-content
[2023-06-16 10:39:25,518] ERROR [_server - 454:_call_behavior] - Exception calling application: [1]  
Traceback (most recent call last):
  File "/kadalu/lib/python3.10/site-packages/grpc/_server.py", line 444, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/nodeserver.py", line 145, in NodeUnpublishVolume
    unmount_volume(request.target_path)
  File "/kadalu/volumeutils.py", line 901, in unmount_volume
    device, _, _ = execute(*cmd)
  File "/kadalu/kadalulib.py", line 187, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  
[2023-06-16 10:39:25,518] ERROR [_server - 454:_call_behavior] - Exception calling application: [1]  

If the node is restarted - allocations won't start with the error:

failed to setup alloc: pre-run hook "csi_hook" failed: rpc error: code = Unknown desc = Exception calling application: [Errno 107] Transport endpoint is not connected: '/mnt/fsn1-gluster-pool/subvol'

kadalu kadalu/kadalu-csi:1.1.0
gluster 10.1-1ubuntu0.1
nomad 1.5.6
docker 5:24.0.2-1~ubuntu.22.04~jammy
Ubuntu 22.04.2 LTS

**Comment by leelavg** [comment]
will track in #948

**Comment by maxadamo** [comment]
@leelavg I noticed that the referenced ticket #948 has been closed. 
On a side note, why do I see a logging type of DEBUG, if I have set `"log-level=INFO"` ? 
For instance:
```
DEBUG [nodeserver - 141:NodeUnpublishVolume] - Received the unmount request volume=a
```

**Comment by leelavg** [comment]
`log-level=INFO` is for gluster and `verbose=yes` in operator env is logging the debug msg.

Yes, original issue is fixed and released.
