### ISSUE TITLE
[Bug]: External Storage will not connect to another GlusterFS host if first is down

### ISSUE THREAD

**Issue by marekvesely-direct** [kadalu/kadalu#1026]
**Describe the bug**
I added External GlusterFS storage to Kadalu storage with 3 GlusterFS hosts, Kadalu Operator trying to connect to first one and if it is down it will not try others.

**To Reproduce**
1. Upload yaml manifest to K8s cluster
```
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: test-storage-class
  namespace: test
spec:
  type: External
  single_pv_per_pool: true
  details:
    gluster_hosts:
      - server-1
      - server-2
      - server-3
    gluster_volname: test-volume
    gluster_options: log-level=DEBUG

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: test
spec:
  storageClassName: kadalu.test-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
     requests:
       storage: 5Gi
```
2. Stop the first GlusterFS server server-1 nad you will see the error:
```
[2023-10-30 09:26:16,529] INFO [kadalulib - 432:monitor_proc] - Restarted Process	 name=operator
[2023-10-30 09:26:16,878] INFO [main - 978:deploy_config_map] - Found existing configmap. Updating	 name=kadalu-info
[2023-10-30 09:26:16,884] INFO [main - 1000:deploy_config_map] - ConfigMap Deployed	 manifest=/kadalu/templates/configmap.yaml uid=83bf34de-aace-42d9-a6cb-28f2e30ae28c upgrade=True
[2023-10-30 09:26:17,610] INFO [main - 966:deploy_csi_pods] - Deployed CSI Pods	 manifest=/kadalu/templates/csi.yaml
[2023-10-30 09:26:17,611] INFO [main - 1059:main] - Upgrading to 	 version=1.2.0
[2023-10-30 09:26:17,616] INFO [main - 311:upgrade_storage_pods] - config map	 volname=test-storage-class data={'volname': 'test-storage-class', 'volume_id': 'c397ad7e-74cd-11ee-ac00-f2b8dbb7d702', 'type': 'External', 'pvReclaimPolicy': 'delete', 'single_pv_per_pool': True, 'gluster_hosts': 'server-1,server-2,server-3', 'gluster_volname': 'test-volume', 'gluster_options': 'log-level=DEBUG'}
[2023-10-30 09:26:18,606] ERROR [kadalulib - 120:is_host_reachable] - Failed to open socket connection	 error=[Errno 113] No route to host host=server-1
Traceback (most recent call last):
2023-10-30T09:26:18.607050352Z   File "/kadalu/main.py", line 1080, in <module>
    main()
  File "/kadalu/main.py", line 1069, in main
    crd_watch(core_v1_client, k8s_client)
  File "/kadalu/main.py", line 911, in crd_watch
    watch_stream(core_v1_client, k8s_client)
  File "/kadalu/main.py", line 898, in watch_stream
    handle_added(core_v1_client, obj)
  File "/kadalu/main.py", line 540, in handle_added
2023-10-30T09:26:18.607867796Z     if not validate_volume_request(obj):
  File "/kadalu/main.py", line 168, in validate_volume_request
    return validate_ext_details(obj)
  File "/kadalu/main.py", line 128, in validate_ext_details
2023-10-30T09:26:18.607999362Z     if not is_host_reachable(ghosts, gport):
2023-10-30T09:26:18.608009100Z   File "/kadalu/kadalulib.py", line 124, in is_host_reachable
    sock.close()
```

**Expected behavior**
If some GlusterFS server will be unavailable it has to connect to another one.

**Actual behavior**
It threw an error specified before and tries to connect only to first server.

**Environment:**
1. If kubectl-kadalu plugin is installed
$ kubectl kadalu version
```
kubectl-kadalu plugin: 1.2.0
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-2hkmq: 1.2.0
pod/kadalu-csi-nodeplugin-w67rw: 1.2.0
pod/kadalu-csi-provisioner-0: 1.2.0
pod/operator-78dbd4df59-5phzs: 1.2.0
```

**Comment by leelavg** [comment]
https://github.com/kadalu/kadalu/blob/77ff63e7f8b21e818c019923f5040d8127b5ac6d/lib/kadalulib.py#L110-L125

> If some GlusterFS server will be unavailable it has to connect to another one.
- based on above code, you should see the Exception for every failed host, however log has only one failure and so it seems the other node is reachable
- is there any log after above error?

**Comment by marekvesely-direct** [comment]
The logs repeated itself over and over, but now I tested outage and it worked as expected. Before we had broken disks on physical machines so from 3 node cluster, there was 1 working node and 2 with really big latency and in healing state. Maybe this was because of this strange thing with hardware, but still one node was working fine (but it was the server-3) and it failing on the first node server-1. I suppose to close this issue now and if it happens again i will raise the ticket.
