### ISSUE TITLE
[Bug]: Error "Failed to open socket connection" while binding PVC

### ISSUE THREAD

**Issue by madoe** [kadalu/kadalu#1051]
**Describe the bug**
We are using Kadalu to connect kubernetes to an external Gluster. In our setup PersistentVolumeClaims will stay in pending state, as Kadalu thinks the Gluster-Nodes are not reachable.

After hours of waiting the PersistentVolumeClaim will eventually succeed.

Studying the code, it turns out Kadalu uses the default ssh port 22 to check the reachability of the gluster server. Our setup uses a non-default port due to security reasons, so this check fails incorrectly.

**To Reproduce**
1. Change SSH-port on external gluster nodes to a different port than 22
2. Create a PVC to bind a volume

**Expected behavior**
The reachability check should be independent of ssh.

**Actual behavior**
The reachability check fails for gluster server with disabled ssh or ssh using non-standard ports.

**Environment:**
 - Kadalu Version: [1.2.0]
 - K8S_DIST: [kubernetes]
 - external gluster with `single_pv_per_pool=true`

**Screenshots or Logs**
```
[2024-04-04 16:47:10,785] ERROR [kadalulib - 120:is_host_reachable] - Failed to open socket connection     error=[Errno 111] Connection refused host=glusterfs-1.example.de
[2024-04-04 16:47:10,786] ERROR [_server - 508:_call_behavior] - Exception calling application: local variable 'sock' referenced before assignment
Traceback (most recent call last):
  File "/kadalu/lib/python3.10/site-packages/grpc/_server.py", line 494, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/controllerserver.py", line 120, in CreateVolume
    volume = search_volume(request.name)
  File "/kadalu/volumeutils.py", line 780, in search_volume
    mount_glusterfs(volume, mntdir)
  File "/kadalu/volumeutils.py", line 926, in mount_glusterfs
    return handle_external_volume(volume, mountpoint, is_client, volume['g_host'])
  File "/kadalu/volumeutils.py", line 1032, in handle_external_volume
    g_host = reachable_host(hosts)
  File "/kadalu/kadalulib.py", line 133, in reachable_host
    if is_host_reachable([host], 22):
  File "/kadalu/kadalulib.py", line 124, in is_host_reachable
    sock.close()
UnboundLocalError: local variable 'sock' referenced before assignment

```

**Comment by madoe** [comment]
After digging further into the code I realized, this check is related to setting quotas on gluster volumes, which is done via SSH. This is also not used in our setup. 
So as a first step the SSH check should only be executed, if quotas are actually being used (See PR 1052).
As second step the used SSH port should be made customizable. Unfortunately my python skills are not sufficient for this task.

**Comment by leelavg** [comment]
> This is also not used in our setup.
- are you mapping 1 gluster volume to 1 PV?

**Comment by madoe** [comment]
Yes, we're mapping 1 external gluster volume to 1 PV.

**Comment by leelavg** [comment]
referenced issue fixes the issue only partially.

**Comment by spermatozoa** [comment]
Maybe glusterd not running?
