### ISSUE TITLE
[Bug]: random exception when mounting the volume on Nomad

### ISSUE THREAD

**Issue by maxadamo** [kadalu/kadalu#1079]
**Describe the bug**

sometimes when I start a container it fails to mount the volume. Then Nomad tries to start the job again, and it succeeds. 

**To Reproduce**
1. start a job
2. from time to time the job fails to start and the job status shows: `Setup Failure    failed to setup alloc: pre-run hook "csi_hook" failed: mounting volumes: rpc error: code = Unknown desc = Exception calling application: [1]`
3. at same time the nodeplugins throws this error: 
```
 [2024-08-21 11:47:20,543] ERROR [volumeutils - 1121:mount_glusterfs_with_host] - mount command failed	 cmd=['/opt/sbin/glusterfs', '--process-name', 'fuse', '-l', '/var/log/gluster/gluster.log', '--volfile-id', 'csi', '--volfile-server', 'test-gluster01.xxx.org', '--volfile-server', 'test-gluster02.xxx.org', '--volfile-server', 'test-gluster03.xxx.org', '--log-level=DEBUG', '/mnt/csi-pool'] error=[1]  
[2024-08-21 11:47:20,544] ERROR [_server - 508:_call_behavior] - Exception calling application: [1]  
Traceback (most recent call last):
  File "/kadalu/lib/python3.10/site-packages/grpc/_server.py", line 494, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/nodeserver.py", line 88, in NodePublishVolume
    mount_glusterfs(volume, mntdir, True)
  File "/kadalu/volumeutils.py", line 929, in mount_glusterfs
    return handle_external_volume(volume, mountpoint, is_client, volume['g_host'])
  File "/kadalu/volumeutils.py", line 1015, in handle_external_volume
    mount_glusterfs_with_host(volname,
  File "/kadalu/volumeutils.py", line 1126, in mount_glusterfs_with_host
    raise excep
  File "/kadalu/volumeutils.py", line 1104, in mount_glusterfs_with_host
    execute(*command)
  File "/kadalu/kadalulib.py", line 182, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1] 
```

**Expected behavior**
Work at the first attempt. 

**Actual behavior**
The nomad job has a retry policy, and it tries a few times. Usually the 2nd time it always succeeds. 

**Environment:**
 - Kadalu Version: container version 1.3
 - Nomad: 1.8

**Screenshots or Logs**
This is the output of `nomad alloc status -verbos <job-id>`:
```
ID                   = f3aedfa8-179b-0405-04f5-dc42270eef92
Eval ID              = 55e636fb-9598-4806-0fd1-7cab452f2212
Name                 = mailserver-in.mailserver-in[0]
Node ID              = 8dd259db-d198-7a12-2bec-7adc53829708
Node Name            = test-nomad01
Job ID               = mailserver-in
Job Version          = 0
Client Status        = failed
Client Description   = Failed tasks
Desired Status       = stop
Desired Description  = alloc was rescheduled because it failed
Created              = 2024-08-21T13:47:20+02:00
Modified             = 2024-08-21T13:47:50+02:00
Deployment ID        = 4cd38657-6cba-cb05-c93f-954c7d91a34f
Deployment Health    = unhealthy
Replacement Alloc ID = e9320792-e265-4ead-15b0-916e362f3828
Evaluated Nodes      = 2
Filtered Nodes       = 0
Exhausted Nodes      = 0
Allocation Time      = 303.001µs
Failures             = 0
Allocation Addresses:
Label        Dynamic  Address
*smtp        yes      83.97.95.193:20405 -> 25
*smtps       yes      83.97.95.193:22143 -> 465
*submission  yes      83.97.95.193:27338 -> 587
Task "mailserver-in" is "dead"
Task Resources:
CPU      Memory   Disk     Addresses
500 MHz  3.0 GiB  300 MiB
CSI Volumes:
Name                 ID                      Plugin      Provider  Schedulable  Read Only  Mount Options
mailserver_in_queue  mailserver_in_queue[0]  kadalu-csi  kadalu    true         false      <none>
Task Events:
Started At     = N/A
Finished At    = 2024-08-21T11:47:20Z
Total Restarts = 0
Last Restart   = N/A
Recent Events:
Time                       Type             Description
2024-08-21T13:47:20+02:00  Alloc Unhealthy  Unhealthy because of failed task
2024-08-21T13:47:20+02:00  Setup Failure    failed to setup alloc: pre-run hook "csi_hook" failed: mounting volumes: rpc error: code = Unknown desc = Exception calling application: [1]
2024-08-21T13:47:20+02:00  Received         Task received by client
Placement Metrics
Node                                  binpack  job-anti-affinity  node-affinity  node-reschedule-penalty  final score
8dd259db-d198-7a12-2bec-7adc53829708  0.37     0                  0              0                        0.37
70e0fc34-071c-7a90-a9c3-cc29b1833992  0.303    0                  0              0                        0.303
```

**Additional context**
n/a

**Comment by maxadamo** [comment]
there have been no new releases. I would like to keep it open.
