### ISSUE TITLE
Got an error while executing kubectl-kadalu command.

### ISSUE THREAD

**Issue by vatsa287** [kadalu/kadalu#138]
```vatsa@vatsa-VirtualBox:~$ sudo kubectl kadalu storage-add storage-pool-2 --device minikube:/home/vatsa/disk/test-storage
Traceback (most recent call last):
  File "/usr/local/bin/kubectl-kadalu", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/kubectl_kadalu/main.py", line 28, in main
    func(args)
  File "/usr/local/lib/python3.6/dist-packages/kubectl_kadalu/storage_add.py", line 129, in subcmd_storage_add
    universal_newlines=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'````

**Comment by sac** [comment]
@vatsa287 it'll be good if you could mention how to reproduce.

**Comment by aravindavk** [comment]
@sac, I got the issue. `capture_output` in subprocess library is introduced in Python 3.7 version. 

Need to use old method to run the commands.
