### ISSUE TITLE
Kadalu error on Minikube

### ISSUE THREAD

**Issue by rajasaur** [kadalu/kadalu#151]
I have been trying to get kadalu working with minikube and it seems to throw this error on minikube.

Environment:
Kubernetes version: 1.15.2
minikube on OSX

```
emerald:istio-1.4.2 raja$ kubectl logs -f server-storage-pool-1-0-minikube-0   -n kadalu --all-containers
+ pid=0
+ cmd=/usr/bin/python3
+ pid=0
+ cmd=/usr/bin/python3
+ script=/kadalu/server.py
+ script=/kadalu/server.py
+ trap 'kill ${!}; term_handler' SIGTERM
+ pid=6
+ trap 'kill ${!}; term_handler' SIGTERM
+ true
+ /usr/bin/python3 /kadalu/server.py
+ wait 7
+ pid=6
+ true
+ /usr/bin/python3 /kadalu/server.py
+ wait 7
+ tail -f /dev/null
Traceback (most recent call last):
+ tail -f /dev/null
  File "/kadalu/server.py", line 33, in <module>
    start_server_process()
  File "/kadalu/server.py", line 26, in start_server_process
    import quotad
[2020-01-26 05:56:34,095] ERROR [glusterfsd - 125:create_and_mount_brick] - Failed to mount export brick	 fstype=xfs device=/dev/sdb mountdir=/bricks/storage-pool-1/data error=[32] b'' b'mount: /bricks/storage-pool-1/data: wrong fs type, bad option, bad superblock on /dev/sdb, missing codepage or helper program, or other error.'
  File "/kadalu/quotad.py", line 9, in <module>
    from .kadalulib import execute, logf, CommandException, \
ImportError: attempted relative import with no known parent package
```

Trying to manually run the mount command threw the same error
```
[root@server-storage-pool-1-0-minikube-0 /]# mount -oprjquota /dev/sdb /bricks/storage-pool-1/data
mount: /bricks/storage-pool-1/data: wrong fs type, bad option, bad superblock on /dev/sdb, missing codepage or helper program, or other error.
```

Looking through dmesg on that container indicates that 
`[ 1248.053406] XFS (sdb): quota support not available in this kernel.`
not sure if thats the reason for the above error.  

How do you go about enabling this? It would be good to add some documentation ( I can provide steps once I can get it working) for testing Kadalu on minikube.

**Comment by rajasaur** [comment]
I have this working on a regular Debian node where I enabled quota support. So it looks like an issue only on minikube.

We can close this issue unless there is something that can be done for minikube users(either with documentation or a workaround)
