### ISSUE TITLE
No `csi` pods are started, urllib3.connection.VerifiedHTTPSConnection object at 0xXXXXXXXXX

### ISSUE THREAD

**Issue by papanito** [kadalu/kadalu#165]
I've cleaned my previous kadalu installation completely. Then I ran

```bash
kubectl create -f https://kadalu.io/operator-latest.yaml
```
But I realized that only `operator`-pod was started but not the `csi`. Here is the log from the `operator`-pod

```golang
+ pid=0
+ cmd=/usr/bin/python3
+ script=/kadalu/main.py
+ trap 'kill ${!}; term_handler' SIGTERM
+ pid=6
+ /usr/bin/python3 /kadalu/main.py
+ true
+ wait 7
+ tail -f /dev/null
2020-01-30 15:33:50,251 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f735c290750>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/namespaces/kadalu/configmaps
[2020-01-30 15:33:50,251] WARNING [connectionpool - 745:urlopen] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f735c290750>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/namespaces/kadalu/configmaps
2020-01-30 15:36:01,323 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f735b84c1d0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/namespaces/kadalu/configmaps
[2020-01-30 15:36:01,323] WARNING [connectionpool - 745:urlopen] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f735b84c1d0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/namespaces/kadalu/configmaps
2020-01-30 15:38:12,395 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f735b84c410>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/namespaces/kadalu/configmaps
[2020-01-30 15:38:12,395] WARNING [connectionpool - 745:urlopen] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f735b84c410>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/namespaces/kadalu/configmaps
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f735b84c610>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kadalu/main.py", line 492, in <module>
    main()
  File "/kadalu/main.py", line 472, in main
    uid = deploy_config_map(core_v1_client)
  File "/kadalu/main.py", line 417, in deploy_config_map
    NAMESPACE)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 11732, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 11832, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 355, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 760, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.43.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/kadalu/configmaps (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f735b84c610>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Reproduction steps**

1. Run `cleanup.sh`

   ```bash
   curl https://raw.githubusercontent.com/kadalu/kadalu/master/extras/scripts/cleanup -o cleanup.sh
   chmod u+x cleanup.sh
   ./cleanup.sh
   ```
2. Check for ns `kadalu` - should be clean

   ```bash
   kubectl -n kadalu get all
   No resources found in kadalu namespace.

   kubectl get ns
   NAME                   STATUS   AGE
   cert-manager           Active   27d
   default                Active   27d
   ingress-nginx          Active   27d
   kube-node-lease        Active   27d
   kube-public            Active   27d
   kube-system            Active   27d
   kubernetes-dashboard   Active   26d
   prometheus             Active   3d3h
   ```
3. Install kadalu

   ```
    kubectl create -f https://kadalu.io/operator-latest.yaml
    namespace/kadalu created
    serviceaccount/kadalu-operator-sa created
    serviceaccount/kadalu-csi-nodeplugin-sa created
    serviceaccount/kadalu-csi-provisioner-sa created
    serviceaccount/kadalu-server-sa created
    customresourcedefinition.apiextensions.k8s.io/kadalustorages.kadalu-operator.storage created
    clusterrole.rbac.authorization.k8s.io/kadalu-operator created
    clusterrolebinding.rbac.authorization.k8s.io/kadalu-operator created
    deployment.apps/operator created

    kubectl -n kadalu get all
    NAME                            READY   STATUS    RESTARTS   AGE
    pod/operator-68649f4bb6-kxpwb   1/1     Running   0          2m23s

    NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
    deployment.apps/operator   1/1     1            1           2m24s

    NAME                                  DESIRED   CURRENT   READY   AGE
    replicaset.apps/operator-68649f4bb6   1         1         1       2m24s
   ```

**Comment by aravindavk** [comment]
Please do not use the bit.ly link. That is pointing to old version.

Use `kubectl create -f https://kadalu.io/operator-latest.yaml` or use the kubectl plugin as https://kadalu.io/docs/k8s-storage/latest/quick-start

**Comment by papanito** [comment]
My bad I took it from [here](https://asciinema.org/a/259949). So now I tried the correct one `kubectl create -f https://kadalu.io/operator-latest.yaml` however there are still no `csi` pods.

```
kubectl create -f https://kadalu.io/operator-latest.yaml
namespace/kadalu created
serviceaccount/kadalu-operator-sa created
serviceaccount/kadalu-csi-nodeplugin-sa created
serviceaccount/kadalu-csi-provisioner-sa created
serviceaccount/kadalu-server-sa created
customresourcedefinition.apiextensions.k8s.io/kadalustorages.kadalu-operator.storage created
clusterrole.rbac.authorization.k8s.io/kadalu-operator created
clusterrolebinding.rbac.authorization.k8s.io/kadalu-operator created
deployment.apps/operator created

kubectl -n kadalu get all                                                                            ─╯
NAME                            READY   STATUS    RESTARTS   AGE
pod/operator-68649f4bb6-kxpwb   1/1     Running   0          2m23s

NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/operator   1/1     1            1           2m24s

NAME                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/operator-68649f4bb6   1         1         1       2m24s
```

**Comment by papanito** [comment]
Apparently there is some sort of timeout, I've added the complete log into the issue description

**Comment by amarts** [comment]
If I start a fresh v0.5 (without any prior kadalu), things seems to be working. Will try a setup after cleanup and see if I can get the same error.

**Comment by papanito** [comment]
@amarts could you reproduce?

**Comment by amarts** [comment]
Found out a theory that, RWO volumes have issues based on hostOS used. Specifically because we use `/dev/loop` way to mount a file on gluster as a block volume. Hence it was not getting reproduced in latest fedora and latest ubuntu host (both of which I use). Looks like CentOS7.x series has an issue right now.

We will find out the possible correct solution and send out an update.

**Comment by papanito** [comment]
Thanks @amarts. If it helps, I'm using `Debian 10`. Is there something which can be done/"cleaned" manually in order to go on?

**Comment by papanito** [comment]
Any updates?

**Comment by amarts** [comment]
> Any updates?

Not today @papanito. Turning out its not easily reproducible in local setup.

**Comment by papanito** [comment]
No problem thanks for looking into it.

**Comment by amarts** [comment]
@papanito I am now suspecting the issue to be from one of my patches:

https://github.com/kadalu/kadalu/commit/b6ad41f2724714089952a1738892fc68fd9d7293#diff-706564578408a7a8e8f703f9dce22096R426 

Can you try adding a 'return None'  @ Line 426 of operator/main.py, and run the `run-local` (https://github.com/kadalu/kadalu/blob/master/extras/scripts/run-local) script ?

**Comment by papanito** [comment]
@amarts will try. Just to be clear, I have to run the `run-local` script on all 3 nodes?

**Comment by amarts** [comment]
Thats a good question.  I prepared 'run-local' for running my tests in my laptop so we can make changes quickly. On a 3 node system, we need to start operator only in one place, but the docker-image tags needs to be present in other machines, so it can consume it. Anyways, Considering we are experimenting to get CSI pod up, I say running it on just 1 node is good enough to see impact. There should be 2 pods anyways.

**Comment by papanito** [comment]
It turned out that the problem was not `kadalu` but the server config. I've added a 3rd node to the cluster which had troubles properly quering the `dns`. This is a known problem with `ntftables` which are default in `Debian 10`. [Using legacy `iptables` fixed the problem](https://wiki.debian.org/nftables)
