### ISSUE TITLE
Traceback found in 0.5.0 CSI controller

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#177]
```
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/controllerserver.py", line 70, in CreateVolume
    if filters['hostvol_type'] == 'External':
KeyError: 'hostvol_type'
```

More info:

```
kubectl get sc --all-namespaces
NAME               PROVISIONER   AGE
kadalu (default)   kadalu        5d4h
kadalu.replica1    kadalu        5d4h
kadalu.replica3    kadalu        5d4h
```

**Comment by amarts** [comment]
More info:

```
I0210 17:58:09.737896       1 controller.go:926] provision "default/data-nextcloud-mariadb-slave-0" class "kadalu": started
I0210 17:58:09.880407       1 controller.go:666] successfully created PV {GCEPersistentDisk:nil AWSElasticBlockStore:nil HostPath:nil Glusterfs:nil NFS:nil RBD:nil ISCSI:nil Cinder:nil CephFS:nil FC:nil Flocker:nil FlexVolume:nil AzureFile:nil VsphereVolume:nil Quobyte:nil AzureDisk:nil PhotonPersistentDisk:nil PortworxVolume:nil ScaleIO:nil Local:nil StorageOS:nil CSI:&CSIPersistentVolumeSource{Driver:org.kadalu.gluster,VolumeHandle:pvc-af314f77-3b8c-4625-a0ce-44501eed8779,ReadOnly:false,FSType:ext4,VolumeAttributes:map[string]string{fstype: xfs,hostvol: storage-pool-main,path: subvol/69/1d/pvc-af314f77-3b8c-4625-a0ce-44501eed8779,pvtype: subvol,storage.kubernetes.io/csiProvisionerIdentity: 1581355599906-8081-kadalu,type: Replica3,},ControllerPublishSecretRef:nil,NodeStageSecretRef:nil,NodePublishSecretRef:nil,}}
I0210 17:58:09.880528       1 controller.go:1026] provision "default/nextcloud-nextcloud" class "kadalu.replica3": volume "pvc-af314f77-3b8c-4625-a0ce-44501eed8779" provisioned
I0210 17:58:09.880561       1 controller.go:1040] provision "default/nextcloud-nextcloud" class "kadalu.replica3": trying to save persistentvolume "pvc-af314f77-3b8c-4625-a0ce-44501eed8779"
I0210 17:58:09.951078       1 controller.go:1047] provision "default/nextcloud-nextcloud" class "kadalu.replica3": persistentvolume "pvc-af314f77-3b8c-4625-a0ce-44501eed8779" saved
I0210 17:58:09.951116       1 controller.go:1088] provision "default/nextcloud-nextcloud" class "kadalu.replica3": succeeded
I0210 17:58:09.951184       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"nextcloud-nextcloud", UID:"af314f77-3b8c-4625-a0ce-44501eed8779", APIVersion:"v1", ResourceVersion:"8570958", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-af314f77-3b8c-4625-a0ce-44501eed8779
I0210 17:58:09.984260       1 controller.go:926] provision "default/data-nextcloud-mariadb-master-0" class "kadalu": started
I0210 17:58:10.135752       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"data-nextcloud-mariadb-slave-0", UID:"7db08caf-0eef-41f9-9ca4-5950089a4464", APIVersion:"v1", ResourceVersion:"8570991", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/data-nextcloud-mariadb-slave-0"
W0210 17:58:10.235790       1 controller.go:685] Retrying syncing claim "default/data-nextcloud-mariadb-slave-0" because failures 0 < threshold 15
E0210 17:58:10.235844       1 controller.go:700] error syncing claim "default/data-nextcloud-mariadb-slave-0": failed to provision volume with StorageClass "kadalu": rpc error: code = Unknown desc = Exception calling application: 'hostvol_type'
```

Shows that as there were no other `storageClass` available, kadalu CSI got called, which crashed the CSI driver. CSI driver needs to have proper checks.

Also probably, kadalu shouldn't be 'default' storageClass, and kadalu.replica1 and kadalu.replica3 should be setup only after storage config is setup.

**Comment by papanito** [comment]
Does this only happen if the default provider is set to `kadalu`?
