### ISSUE TITLE
external storage config options not handled properly

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#204]
```
Traceback (most recent call last):
  File "/kadalu/main.py", line 540, in <module>
    main()
  File "/kadalu/main.py", line 535, in main
    crd_watch(core_v1_client, k8s_client)
  File "/kadalu/main.py", line 416, in crd_watch
    handle_added(core_v1_client, obj)
  File "/kadalu/main.py", line 354, in handle_added
    handle_external_storage_addition(core_v1_client, obj)
  File "/kadalu/main.py", line 308, in handle_external_storage_addition
    execute(KUBECTL_CMD, "create", "-f", filename)
  File "/kadalu/kadalulib.py", line 106, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  error: error validating "/kadalu/templates/external-storageclass.yaml": error validating data: unknown object type "nil" in StorageClass.parameters.gluster_options; if you choose to ignore these errors, turn validation off with --validate=false
```

This trace is seen when using `kubectl kadalu` CLI tool

**Comment by amarts** [comment]
Noticed that this is happening because `gluster-options` field is not provided, and in operator, if this option is not provided, it is taking nil (empty string) as option, and while dumping the json to config map, that gives an error.
