### ISSUE TITLE
hostvoltype might be NONE

### ISSUE THREAD

**Issue by close2** [kadalu/kadalu#277]
When creating your own storageclass the hostvoltype might not be set.

Normally kadalu storage classes have the parameter `hostvol_type`:
`kubectl get storageclasses.storage.k8s.io kadalu.replica1 -o yaml`
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2020-07-07T12:20:03Z"
  name: kadalu.replica1
  resourceVersion: "11672"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/kadalu.replica1
  uid: 7761a3a0-14fd-4600-83ca-b98d333a8738
parameters:
  hostvol_type: Replica1
provisioner: kadalu
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

However if we create our own storageClass:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kadalu.fast-storage
provisioner: kadalu
parameters:
  storage_name: "storage-pool-1"
```
This parameter is missing:
`kubectl get storageclasses.storage.k8s.io kadalu.fast-storage -o yaml`
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2020-07-11T19:33:43Z"
  name: kadalu.fast-storage
  resourceVersion: "1358515"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/kadalu.fast-storage
  uid: e2c9becf-da44-4bbc-9585-344fa480a612
parameters:
  storage_name: "storage-pool-1"
provisioner: kadalu
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

The createVolumeReponse then fails.

https://github.com/kadalu/kadalu/blob/274934b3c102391ac2a9a61059e77194d93926ab/csi/controllerserver.py#L205

**Comment by close2** [comment]
Here is the log output
`kubectl -n kadalu logs csi-provisioner-0 -c kadalu-provisioner`
```
[2020-07-14 08:55:43,860] INFO [controllerserver - 198:CreateVolume] - Volume created    name=pvc-8cca9a18-084a-4baf-a074-626edf483b9e size=1073741824 hostvol=storage-pool-unsafe2 pvtype=subvol volpath=subvol/69/4a/pvc-8cca9a18-084a-4baf-a074-626edf483b9e duration_seconds=0.016809940338134766
[2020-07-14 08:55:43,862] DEBUG [volumeutils - 209:update_free_size] - Updated .stat.tmp file    hostvol=storage-pool-unsafe2 before=2425366037504 after=2424292295680
[2020-07-14 08:55:43,863] DEBUG [volumeutils - 215:update_free_size] - Renamed .stat.tmp to .stat file   hostvol=storage-pool-unsafe2
[2020-07-14 08:55:43,865] DEBUG [connectionpool - 941:_new_conn] - Starting new HTTPS connection (1): www.google-analytics.com:443
[2020-07-14 08:55:43,905] DEBUG [connectionpool - 442:_make_request] - https://www.google-analytics.com:443 "GET /collect?v=1&t=pageview&dl=http://kadalu.org/kadalu-pvc-None-0.7.0&dt=Kadalu%20pvc-None&tid=UA-144588868-1&cid=cd925f26-aacb-4b84-9fae-83aead7cdf07 HTTP/1.1" 200 35
[2020-07-14 08:55:43,907] ERROR [_server - 445:_call_behavior] - Exception calling application: None has type NoneType, but expected one of: bytes, unicode
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/controllerserver.py", line 213, in CreateVolume
    "fstype": "xfs"
  File "/usr/lib64/python3.7/_collections_abc.py", line 841, in update
    self[key] = other[key]
TypeError: None has type NoneType, but expected one of: bytes, unicode
```

**Comment by amarts** [comment]
Thanks..

looks like the right fix is to check for it before submission...

**Comment by close2** [comment]
i've updated my comment.
The problem is in the createVolumeResponse call.

The `volume` https://github.com/kadalu/kadalu/blob/6519bcec6d164ca6f8b9c0684459fc7bbe347469/csi/protos/csi.proto#L415
doesn't allow None as value.

This value should exist inside `hostvol` (it's the `type` in the `.info` file).
You could probably also simply pass "unknown" if it is `None`.  (I don't know if this value is ever used afterwards).

If it isn't used the `CreateVolumeResponse` could also omit it when building the `volume` object.
