### ISSUE TITLE
Issue while running latest version on k8s 1.13.7

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#306]
```
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.96.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
[2020-09-22 11:11:44,670] DEBUG [rest - 228:request] - response body: {
  "major": "1",
  "minor": "13",
  "gitVersion": "v1.13.7",
  "gitCommit": "4683545293d792934a7a7e12f2cc47d20b2dd01b",
  "gitTreeState": "clean",
  "buildDate": "2019-06-06T01:39:30Z",
  "goVersion": "go1.11.5",
  "compiler": "gc",
  "platform": "linux/amd64"
}
Traceback (most recent call last):
  File "/kadalu/main.py", line 552, in <module>
    main()
  File "/kadalu/main.py", line 535, in main
    deploy_csi_pods(core_v1_client)
  File "/kadalu/main.py", line 452, in deploy_csi_pods
    execute(KUBECTL_CMD, CREATE_CMD, "-f", filename)
  File "/kadalu/kadalulib.py", line 122, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  unable to recognize "/kadalu/templates/csi-driver-crd.yaml": no matches for kind "CSIDriver" in version "csi.storage.k8s.io/v1alpha1"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"
Name: "csidrivers.csi.storage.k8s.io", Namespace: ""
from server for: "/kadalu/templates/csi-driver-crd.yaml": customresourcedefinitions.apiextensions.k8s.io "csidrivers.csi.storage.k8s.io" is forbidden: User "system:serviceaccount:kadalu:kadalu-operator" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

**Comment by amarts** [comment]
Took out the tests on 1.13.x, most users of kadalu are using 1.16 or above right now. If there are concerns we will look into.
