### ISSUE TITLE
"kubectl kadalu storage-list --status" throws kubectl exec deprecation error

### ISSUE THREAD

**Issue by floek** [kadalu/kadalu#357]
Hi,
when I exec `kubectl kadalu storage-list --status`I'm getting the following error for every storage, which has no PV yet:

```
Failed to get size details of the storage "kicton-worker-0-pool"
error 1 kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
command terminated with exit code 1
```

Storages with Pas deployed are working as expected.

Floek

**Comment by amarts** [comment]
Looks like this is fixed with #321, as there is only one 'exec' command in there. Will have a look soon.

**Comment by amarts** [comment]
Is this fixed with `0.7.6`? If not, we will try to prioritize this.

**Comment by floek** [comment]
No, there is a new error in 0.7.6:
```console
> kubectl kadalu version
kubectl-kadalu 0.7.6
> kubectl kadalu storage-list --status
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/kubectl-kadalu/__main__.py", line 64, in <module>
  File "/usr/local/bin/kubectl-kadalu/__main__.py", line 53, in main
  File "/usr/local/bin/kubectl-kadalu/storage_list.py", line 237, in run
  File "/usr/local/bin/kubectl-kadalu/storage_list.py", line 197, in fetch_status
IndexError: list index out of range
root@controller1.int:~ #
```

**Comment by camrossi** [comment]
@floek does it actually work the storage provisioning for you ?

I have a very similar issue (0.7.6 on K8S 1.18)
```
kubectl kadalu storage-list --status
Failed to get size details of the storage "storage-pool-1"
error 126 command terminated with exit code 126
Name             Type        Utilization            Pvs Count      Min PV Size      Avg PV Size      Max PV Size
storage-pool-1   Replica1    0/0 (0%)                       0                0                0                0

# kgpvc
NAME   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
pv1    Bound    pvc-5dd22e27-3614-419c-b55e-d03f00f8d76a   1Gi        RWX            kadalu.replica1   2m9s
```
But then the POD will not manage to mount anything:
```
  Warning  FailedMount             8s (x9 over 2m16s)  kubelet, fab2-k8s-4      MountVolume.NewMounter initialization failed for volume "pvc-5dd22e27-3614-419c-b55e-d03f00f8d76a" : kubernetes.io/csi: expected valid fsGroupPolicy, received nil value or empty string
```

Also there is no sign of the PVC in the  storage-list command and furthermore if I create a PVC bigger than my actual drive it gets `Bound` anyway. 

Also I noticed it still tries to call sqlite3 executable and is missing as it was for #321 ?

**Comment by floek** [comment]
Hi @camrossi 
I'm using an external Gluster Server in the meantime and for me the storage provisioning works. The error in this issue is just a display error for me.
Maybe the kadalu team can help.

Cheers,
floek

**Comment by aravindavk** [comment]
This is now fixed https://github.com/kadalu/kadalu/pull/323
