### ISSUE TITLE
Uncaught exception on kubectl kadalu storage-list --status

### ISSUE THREAD

**Issue by floek** [kadalu/kadalu#359]
Hi,

I get an uncaught exception on running `kubectl kadalu storage-list --status` now:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/kubectl-kadalu/__main__.py", line 58, in <module>
  File "/usr/local/bin/kubectl-kadalu/__main__.py", line 50, in main
  File "/usr/local/bin/kubectl-kadalu/storage_list.py", line 236, in run
  File "/usr/local/bin/kubectl-kadalu/storage_list.py", line 211, in fetch_status
ValueError: could not convert string to float:
```

What I did:
  * created storage
  * created PVCs
  * deleted PVCs and PVs
  * run `kubectl kadalu storage-list --status`

**Comment by FlexibleToast** [comment]
I can recreate using these steps as well as if a pvc is stuck in pending status. For example if you create a PVC too large to be assigned to the PVC gets stuck pending and `kubectl kadalu storage-list --status` shows the same error
```
$ k get pvc
NAME          STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
sample-pvc    Bound     pvc-d3ba6f6e-c13c-4a8f-a657-6cb8f229015c   95Gi       RWO            kadalu.replica2   86s
sample2-pvc   Pending                                                                        kadalu.replica2   28s
$ k kadalu storage-list --status
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/kubectl-kadalu/__main__.py", line 58, in <module>
  File "/usr/local/bin/kubectl-kadalu/__main__.py", line 50, in main
  File "/usr/local/bin/kubectl-kadalu/storage_list.py", line 235, in run
  File "/usr/local/bin/kubectl-kadalu/storage_list.py", line 211, in fetch_status
ValueError: could not convert string to float:
```
