### ISSUE TITLE
operator exception: "Connection refused"

### ISSUE THREAD

**Issue by floek** [kadalu/kadalu#391]
Hi,

it's me again ;-). I reinstalled kadalu 0.7.4 and now I get an "Connection refused" exception from the operator. Also no other pods where created. Here is the exception:

```
[2020-12-23 08:49:09,298] WARNING [connectionpool - 780:urlopen] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97b4cbd580>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/kadalu/configmaps
[2020-12-23 08:49:09,299] WARNING [connectionpool - 780:urlopen] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97b4cbd730>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/kadalu/configmaps
[2020-12-23 08:49:09,300] WARNING [connectionpool - 780:urlopen] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97b4cbd820>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/kadalu/configmaps
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f97b4cbd9a0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kadalu/main.py", line 811, in <module>
    main()
  File "/kadalu/main.py", line 791, in main
    uid = deploy_config_map(core_v1_client)
  File "/kadalu/main.py", line 723, in deploy_config_map
    configmaps = core_v1_client.list_namespaced_config_map(
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api/core_v1_api.py", line 14507, in list_namespaced_config_map
    return self.list_namespaced_config_map_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api/core_v1_api.py", line 14618, in list_namespaced_config_map_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/rest.py", line 212, in request
    r = self.pool_manager.request(method, url,
  File "/usr/local/lib/python3.8/dist-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/namespaces/kadalu/configmaps (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97b4cbd9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Looks like, the operator can't talk to the k8s-api.
I've had no other changes in my setup.

Greetings,

floek

**Comment by floek** [comment]
An update: I manually changed the operators container version to docker.io/kadalu/kadalu-operator:v0.7.2 and now the node plugin containers get created. So it seems to be a problem with the updated containers.

**Comment by amarts** [comment]
Intermediate version change was the reason indeed... you have 0.7.4 tag now available.

What we are building is `devel` tag updated for every PR push, and release tags are updated upon release along with latest tag.

**Comment by amarts** [comment]
For the record - this 'Connection refused is specific to 'kubernetes==12.+' version used, when we use `kuberenetes==11.0.0` it is fine (this is the python pypi package).

**Comment by floek** [comment]
This error is gone now. Thank you.
