### ISSUE TITLE
Python exception "TypeError: unhashable type: 'list'" with external GlusterFS on 0.7.4

### ISSUE THREAD

**Issue by floek** [kadalu/kadalu#393]
Hi,

after fixing #376 I now get another Python exception when executing kubectl kadalu storage-list:
```
# kubectl kadalu storage-list
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/kubectl-kadalu/__main__.py", line 64, in <module>
  File "/usr/local/bin/kubectl-kadalu/__main__.py", line 53, in main
  File "/usr/local/bin/kubectl-kadalu/storage_list.py", line 235, in run
  File "/usr/local/bin/kubectl-kadalu/storage_list.py", line 72, in list_storages
TypeError: unhashable type: 'list'
```

Cheers,

floek

**Comment by amarts** [comment]
@vatsa287 fyi... see if you can add it as a test in tests/minikube.sh That way, we can make sure the changes are immediately confirmed to be working!

**Comment by vatsa287** [comment]
sure I'll add it

**Comment by floek** [comment]
This still exists in 0.7.5:
```
# kubectl-kadalu version
kubectl-kadalu 0.7.5
# kubectl kadalu storage-list
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/kubectl-kadalu/__main__.py", line 64, in <module>
  File "/usr/local/bin/kubectl-kadalu/__main__.py", line 53, in main
  File "/usr/local/bin/kubectl-kadalu/storage_list.py", line 235, in run
  File "/usr/local/bin/kubectl-kadalu/storage_list.py", line 72, in list_storages
TypeError: unhashable type: 'list'
```
