### ISSUE TITLE
kadalu-nodeplugin: Exception calling application: [Errno 2] No such file or directory: '/var/lib/gluster/ext-pool.info'

### ISSUE THREAD

**Issue by floek** [kadalu/kadalu#400]
Hi,

here is another exception I got with 0.7.5. Also from the kadalu-nodeplugin container (using an external Gluster Storage) and maybe related to #399. This one appeared only once.

```
[2020-12-24 06:49:36,857] DEBUG [nodeserver - 41:NodePublishVolume] - Received the mount request	 volume=pvc-f14a4200-6a8a-43cb-8b15-2ed7825c63ca voltype=unknown hostvol=ext-pool pvpath=subvol/9f/c7/pvc-f14a4200-6a8a-43cb-8b15-2ed7825c63ca pvtype=subvol
[2020-12-24 06:49:36,872] ERROR [_server - 445:_call_behavior] - Exception calling application: [Errno 2] No such file or directory: '/var/lib/gluster/ext-pool.info'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/nodeserver.py", line 72, in NodePublishVolume
    mount_glusterfs(volume, mntdir)
  File "/kadalu/volumeutils.py", line 611, in mount_glusterfs
    generate_client_volfile(volume['name'])
  File "/kadalu/volumeutils.py", line 556, in generate_client_volfile
    with open(info_file_path) as info_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/gluster/ext-pool.info'
```

Cheers,

floek

**Comment by amarts** [comment]
While I was not able to reproduce this, I ran few tests with `0.7.6` version, and things seems to be fine. Please check if its all fine now.

**Comment by floek** [comment]
Haven't seen this yet in 0.7.6.

**Comment by amarts** [comment]
This is indeed caused by #399 itself. #416 fixes this too.
