### ISSUE TITLE
PVC stuck pending using k3os on arm

### ISSUE THREAD

**Issue by FlexibleToast** [kadalu/kadalu#424]
I installed k3os on 4 raspberry pis. I deployed k3s using the --disable local-storage option so that it doesn't auto deploy the local host storage provisioner with the intention of using kadalu instead. Because I'm using arm, I have to use a release version of kadalu so I installed using
`kubectl apply -f https://github.com/kadalu/kadalu/releases/download/0.7.6/kadalu-operator.yaml`
After kadalu fully deployed I crated a storage pool using
`kubectl kadalu storage-add --type Replica2 --device pikubed-m0:/dev/md0 --device pikubed-m2:/dev/md0 storage-m0-m2`
Then I created a pvc using

```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-pvc
spec:
  storageClassName: kadalu.replica2
  accessModes:
    - ReadWriteOnce # You can also provide 'ReadWriteMany' here
  resources:
    requests:
      storage: 5Gi
```

This is when I encounter the problems. At this point the pvc gets stuck at pending.

```
$ k get pvc
NAME         STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS      AGE
sample-pvc   Pending                                      kadalu.replica2   59s
```

Looking into it further

```
k describe pvc sample-pvc
Name:          sample-pvc
Namespace:     default
StorageClass:  kadalu.replica2
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kadalu
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                   From                                                                  Message
  ----     ------                ----                  ----                                                                  -------
  Normal   Provisioning          102s (x9 over 5m59s)  kadalu_kadalu-csi-provisioner-0_606642ea-cc6e-4c92-b1b1-57c6a9eae980  External provisioner is provisioning volume for claim "default/sample-pvc"
  Warning  ProvisioningFailed    102s (x9 over 5m58s)  kadalu_kadalu-csi-provisioner-0_606642ea-cc6e-4c92-b1b1-57c6a9eae980  failed to provision volume with StorageClass "kadalu.replica2": rpc error: code = Unknown desc = Exception calling application: [1]
  Normal   ExternalProvisioning  15s (x24 over 5m59s)  persistentvolume-controller                                           waiting for a volume to be created, either by external provisioner "kadalu" or manually created by system administrator
```

So, I looked at the `kadalu-csi-provisioner-0` pod logs for clues on what is happening. The `csi-provisioner` container has this repeating over and over in its logs.

```
I0123 18:11:36.063248       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"sample-pvc", UID:"ed319a71-b378-4fb1-ad51-9c744861fac8", APIVersion:"v1", ResourceVersion:"12646", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "kadalu.replica2": rpc error: code = Unknown desc = Exception calling application: [1]  
E0123 18:11:36.063644       1 controller.go:966] error syncing claim "ed319a71-b378-4fb1-ad51-9c744861fac8": failed to provision volume with StorageClass "kadalu.replica2": rpc error: code = Unknown desc = Exception calling application: [1]  
I0123 18:11:37.064075       1 controller.go:1317] provision "default/sample-pvc" class "kadalu.replica2": started
I0123 18:11:37.064930       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"sample-pvc", UID:"ed319a71-b378-4fb1-ad51-9c744861fac8", APIVersion:"v1", ResourceVersion:"12646", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/sample-pvc"
```

kadalu-provisioner

```
[2021-01-23 18:12:40,006] ERROR [_server - 445:_call_behavior] - Exception calling application: [1]  
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/controllerserver.py", line 179, in CreateVolume
    hostvol = mount_and_select_hosting_volume(host_volumes, pvsize)
  File "/kadalu/volumeutils.py", line 214, in mount_and_select_hosting_volume
    mount_glusterfs(volume, mntdir)
  File "/kadalu/volumeutils.py", line 824, in mount_glusterfs
    raise err
  File "/kadalu/volumeutils.py", line 816, in mount_glusterfs
    execute(*cmd)
  File "/kadalu/kadalulib.py", line 120, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  
[2021-01-23 18:13:44,015] DEBUG [controllerserver - 36:CreateVolume] - Create Volume request     request=name: "pvc-ed319a71-b378-4fb1-ad51-9c744861fac8"
capacity_range {
  required_bytes: 5368709120
}
volume_capabilities {
  mount {
  }
  access_mode {
    mode: SINGLE_NODE_WRITER
  }
}
parameters {
  key: "hostvol_type"
  value: "Replica2"
}

[2021-01-23 18:13:44,016] DEBUG [controllerserver - 55:CreateVolume] - Found PV type     pvtype=subvol capabilities=[mount {
}
access_mode {
  mode: SINGLE_NODE_WRITER
}
]
[2021-01-23 18:13:44,017] DEBUG [controllerserver - 68:CreateVolume] - Filters applied to choose storage         hostvol_type=Replica2
[2021-01-23 18:13:44,018] DEBUG [controllerserver - 79:CreateVolume] - Got list of hosting Volumes       volumes=storage-m0-m2
```

kadalu-logging

```
[2021-01-23 18:11:36.047522] I [MSGID: 100030] [glusterfsd.c:2865:main] 0-/usr/sbin/glusterfs: Started running /usr/sbin/glusterfs version 7.2 (args: /usr/sbin/glusterfs --process-name fuse -l /var/log/gluster/gluster.log --volfile-id storage-m0-m2 -f /kadalu/volfiles/storage-m0-m2.client.vol /mnt/storage-m0-m2) 
[2021-01-23 18:11:36.050405] E [mount.c:468:gf_fuse_mount] 0-glusterfs-fuse: cannot open /dev/fuse (No such file or directory)
[2021-01-23 18:11:36.050504] E [MSGID: 101019] [xlator.c:626:xlator_init] 0-fuse: Initialization of volume 'fuse' failed, review your volfile again 
[2021-01-23 18:11:37.209505] I [MSGID: 100030] [glusterfsd.c:2865:main] 0-/usr/sbin/glusterfs: Started running /usr/sbin/glusterfs version 7.2 (args: /usr/sbin/glusterfs --process-name fuse -l /var/log/gluster/gluster.log --volfile-id storage-m0-m2 -f /kadalu/volfiles/storage-m0-m2.client.vol /mnt/storage-m0-m2) 
[2021-01-23 18:11:37.212103] E [mount.c:468:gf_fuse_mount] 0-glusterfs-fuse: cannot open /dev/fuse (No such file or directory)
[2021-01-23 18:11:37.212197] E [MSGID: 101019] [xlator.c:626:xlator_init] 0-fuse: Initialization of volume 'fuse' failed, review your volfile again
```

**Comment by amarts** [comment]
I haven't made a release with arm on 0.8.0 yet. Let me try to push it soon! Lets see if these are resolved by then.

**Comment by amarts** [comment]
had missed updating this earlier. With 0.8.6 all known issues with ARM64 specific things are fixed. Please try upgrading to 0.8.6
