### ISSUE TITLE
Error when adding devices /dev/disk/by-id/*

### ISSUE THREAD

**Issue by hans-fischer** [kadalu/kadalu#427]
Hello together!

I tried to add my devices by-id because it's consistent when rebooting the cluster.

My command I execute is: 
`kubectl kadalu storage-add storage-pool-1 --device node2:/dev/disk/by-id/usb-SanDisk_Ultra_4C530001061023116262-0:0`

The error:
```
The following nodes are available:
  node1, node2, node3, node4, node5, node6

Traceback (most recent call last):
  File "/Users/hfi/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/hfi/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/kubectl-kadalu/__main__.py", line 58, in <module>
  File "/usr/local/bin/kubectl-kadalu/__main__.py", line 47, in main
  File "/usr/local/bin/kubectl-kadalu/storage_add.py", line 231, in run
  File "/usr/local/bin/kubectl-kadalu/storage_add.py", line 189, in storage_add_data
ValueError: too many values to unpack (expected 2)
```

The problem is that the device-id contains a ':'.

In my opinion the fix would be:
File: cli/kubectl_kadalu/storage_add.py
by changing line: 190
FROM: .split(":")
TO: .split(":", 1)

Is that a valid solution?

**Comment by aravindavk** [comment]
> Is that a valid solution?

Yes, That will fix the issue. Thanks for sharing.

**Comment by hans-fischer** [comment]
Are there any other parsings doing this?

**Comment by aravindavk** [comment]
Sent PR to fix the issue. https://github.com/kadalu/kadalu/pull/428

Thanks
