### ISSUE TITLE
Exception calling application: unable to open database  file

### ISSUE THREAD

**Issue by matulek** [kadalu/kadalu#451]
Hello,

I'm trying to follow a basic setup and I can't create a volume. When I'm trying to create PVC, it's in "pending state" and I see errors in CSI provisioner. They seem to be related to SQLite databse creation process.

(I've tried Replica3 before and had the same error, I've deleted Replica3 storage pool and went back to try Replica1, the log seems to contain some messages related to previous setup, but the main issue remains the same)

Here's log:

```
[2021-02-21 21:18:31,840] DEBUG [controllerserver - 37:CreateVolume] - Create Volume request     request=name: "pvc-66d
87eec-5653-496f-b6c9-5425b2347933"                                                                                     
capacity_range {                                                                                                       
  required_bytes: 100000000                                                                                            
}       
volume_capabilities {                                                                                                  
  mount {                                                                                                              
  }  
  access_mode {                                            
    mode: MULTI_NODE_MULTI_WRITER                                                                                      
  }                                                        
}                                                                                                                      
parameters {                                                                                                           
  key: "hostvol_type"                                                                                                  
  value: "Replica1"                                        
}                                                          

[2021-02-21 21:18:31,841] DEBUG [controllerserver - 56:CreateVolume] - Found PV type     pvtype=subvol capabilities=[mo
unt {                                                      
}
access_mode {
  mode: MULTI_NODE_MULTI_WRITER
}
]
[2021-02-21 21:18:31,841] DEBUG [controllerserver - 69:CreateVolume] - Filters applied to choose storage         hostvo
l_type=Replica1
[2021-02-21 21:19:01,579] DEBUG [volumeutils - 159:get_pv_hosting_volumes] - Volume doesn't match the filter     volnam
e=storage-pool-1 hostvol_type=Replica3
[2021-02-21 21:19:01,580] DEBUG [controllerserver - 80:CreateVolume] - Got list of hosting Volumes       volumes=
[2021-02-21 21:19:01,580] ERROR [controllerserver - 205:CreateVolume] - No Hosting Volumes available, add more storage
[2021-02-21 21:19:01,867] DEBUG [controllerserver - 80:CreateVolume] - Got list of hosting Volumes       volumes=storag
e-pool-1
[2021-02-21 21:19:01,893] DEBUG [volumeutils - 812:mount_glusterfs] - Already mounted    mount=/mnt/storage-pool-1
[2021-02-21 21:19:01,898] ERROR [_server - 445:_call_behavior] - Exception calling application: unable to open database
 file
Traceback (most recent call last):
  File "/kadalu/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/controllerserver.py", line 202, in CreateVolume
    hostvol = mount_and_select_hosting_volume(host_volumes, pvsize)
  File "/kadalu/volumeutils.py", line 220, in mount_and_select_hosting_volume
    with SizeAccounting(hvol, mntdir) as acc:
  File "/kadalu/kadalulib.py", line 187, in __enter__
    self.conn = sqlite3.connect(os.path.join(self.mount_path, DB_NAME))
sqlite3.OperationalError: unable to open database file
```

**Comment by amarts** [comment]
which version of kadalu did you install?

**Comment by amarts** [comment]
also, another thing to note, what is the host OS ?

**Comment by amarts** [comment]
Was not able to reproduce or see the similar traces in setup.

If you are still setting up, can you consider using version [0.8.0](https://github.com/kadalu/kadalu/releases/tag/0.8.0) version?
