### ISSUE TITLE
DNS and reserved ports issue on OpenShift 4.7

### ISSUE THREAD

**Issue by rmey** [kadalu/kadalu#585]
I could not get kadalu.replica3 mode working with an OpenShift Cluster having 3 workers with attached storage on /dev/vdd each. In the logs I get DNS and reserved port warnings. The replication does not work - every of the 3 example pods which share a RWX PVC with replica3 mode storage class are looking like as they would have their own volume. The shared volume does not work.
Since the log is very big I created a gist:
[Full logs and example yamls](https://gist.github.com/rmey/6f162e2269c19f31fc2e096694aea51c)
```
...
[2021-06-23 09:04:29.086639 +0000] I [MSGID: 101190] [event-epoll.c:669:event_dispatch_epoll_worker] 0-epoll: Started thread with index [{index=0}] 
[2021-06-23 09:04:29.086726 +0000] I [MSGID: 101190] [event-epoll.c:669:event_dispatch_epoll_worker] 0-epoll: Started thread with index [{index=1}] 
[2021-06-23 09:04:32.062417 +0000] E [MSGID: 101075] [common-utils.c:519:gf_resolve_ip6] 0-resolver: error in getaddrinfo [{family=0}, {ret=Name or service not known}] 
[2021-06-23 09:04:32.062479 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-0: DNS resolution failed on host server-storage-pool1-0-0.storage-pool1
[2021-06-23 09:04:32.064563 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-1: DNS resolution failed on host server-storage-pool1-1-0.storage-pool1
[2021-06-23 09:04:32.067209 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-2: DNS resolution failed on host server-storage-pool1-2-0.storage-pool1
[2021-06-23 09:04:35.064844 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-0: DNS resolution failed on host server-storage-pool1-0-0.storage-pool1
[2021-06-23 09:04:35.066737 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-1: DNS resolution failed on host server-storage-pool1-1-0.storage-pool1
[2021-06-23 09:04:35.069133 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-2: DNS resolution failed on host server-storage-pool1-2-0.storage-pool1
[2021-06-23 09:04:38.067140 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-0: DNS resolution failed on host server-storage-pool1-0-0.storage-pool1
[2021-06-23 09:04:38.068875 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-1: DNS resolution failed on host server-storage-pool1-1-0.storage-pool1
[2021-06-23 09:04:38.071035 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-2: DNS resolution failed on host server-storage-pool1-2-0.storage-pool1
The message "E [MSGID: 101075] [common-utils.c:519:gf_resolve_ip6] 0-resolver: error in getaddrinfo [{family=0}, {ret=Name or service not known}]" repeated 8 times between [2021-06-23 09:04:32.062417 +0000] and [2021-06-23 09:04:38.071032 +0000]
[2021-06-23 09:04:41.069063 +0000] W [MSGID: 101012] [common-utils.c:3275:gf_get_reserved_ports] 0-glusterfs: could not open/read file, getting ports info [{ /proc/sys/net/ipv4/ip_local_reserved_ports}, {errno=2}, {error=No such file or directory}] 
[2021-06-23 09:04:41.069128 +0000] W [MSGID: 101081] [common-utils.c:3311:gf_process_reserved_ports] 0-glusterfs: Not able to get reserved ports, hence there is a possibility that glusterfs may consume reserved port [] 
[2021-06-23 09:04:41.071308 +0000] E [MSGID: 101075] [common-utils.c:519:gf_resolve_ip6] 0-resolver: error in getaddrinfo [{family=0}, {ret=Name or service not known}] 
[2021-06-23 09:04:41.071334 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-1: DNS resolution failed on host server-storage-pool1-1-0.storage-pool1
[2021-06-23 09:04:41.073410 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-2: DNS resolution failed on host server-storage-pool1-2-0.storage-pool1
[2021-06-23 09:04:41.073407 +0000] E [MSGID: 101075] [common-utils.c:519:gf_resolve_ip6] 0-resolver: error in getaddrinfo [{family=0}, {ret=Name or service not known}] 
[2021-06-23 09:04:41.074920 +0000] I [MSGID: 114057] [client-handshake.c:1126:select_server_supported_programs] 0-storage-pool1-client-0: Using Program [{Program-name=GlusterFS 4.x v1}, {Num=1298437}, {Version=400}] 
[2021-06-23 09:04:41.078958 +0000] I [MSGID: 114046] [client-handshake.c:855:client_setvolume_cbk] 0-storage-pool1-client-0: Connected, attached to remote volume [{conn-name=storage-pool1-client-0}, {remote_subvol=/bricks/storage-pool1/data/brick}] 
[2021-06-23 09:04:41.078997 +0000] I [MSGID: 108005] [afr-common.c:6046:__afr_handle_child_up_event] 0-storage-pool1-replica-0: Subvolume 'storage-pool1-client-0' came back up; going online. 
[2021-06-23 09:04:44.074163 +0000] E [MSGID: 101075] [common-utils.c:519:gf_resolve_ip6] 0-resolver: error in getaddrinfo [{family=0}, {ret=Name or service not known}] 
[2021-06-23 09:04:44.074214 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-1: DNS resolution failed on host server-storage-pool1-1-0.storage-pool1
[2021-06-23 09:04:44.076018 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-pool1-client-2: DNS resolution failed on host server-storage-pool1-2-0.storage-pool1
[2021-06-23 09:04:45.817828 +0000] I [addr.c:52:compare_addr_and_update] 0-/bricks/storage-pool1/data/brick: allowed = "*", received addr = "172.30.176.47"
[2021-06-23 09:04:45.817873 +0000] I [MSGID: 115029] [server-handshake.c:564:server_setvolume] 0-storage-pool1-server: accepted client from CTX_ID:c37f39a2-c581-4f3a-91e0-f01bc722abe6-GRAPH_ID:0-PID:11-HOST:server-storage-pool1-0-0-PC_NAME:storage-pool1-client-1-RECON_NO:-0 (version: 2021.06.21) with subvol /bricks/storage-pool1/data/brick 
[2021-06-23 09:04:45.822531 +0000] I [rpcsvc.c:850:rpcsvc_handle_rpc_call] 0-rpc-service: spawned a request handler thread for queue 0
[
...
```
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv2
spec:
  storageClassName: kadalu.replica3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nfs-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: pv2
        persistentVolumeClaim:
          claimName: pv2
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: pv2 # name of volume should match claimName volume
          mountPath: mydata
```

**Comment by amarts** [comment]
```
[2021-06-23 09:24:31,205] INFO [main - 464:deploy_server_pods] - Deployed Server pod	 volname=storage-pool1 manifest=/kadalu/templates/server.yaml node=172.17.2.4
Traceback (most recent call last):
  File "/kadalu/lib/python3.8/site-packages/urllib3/response.py", line 697, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kadalu/lib/python3.8/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/kadalu/lib/python3.8/site-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/kadalu/lib/python3.8/site-packages/urllib3/response.py", line 701, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kadalu/main.py", line 1002, in <module>
    main()
  File "/kadalu/main.py", line 991, in main
    crd_watch(core_v1_client, k8s_client)
  File "/kadalu/main.py", line 844, in crd_watch
    for event in k8s_watch.stream(crds.list_cluster_custom_object,
  File "/kadalu/lib/python3.8/site-packages/kubernetes/watch/watch.py", line 144, in stream
    for line in iter_resp_lines(resp):
  File "/kadalu/lib/python3.8/site-packages/kubernetes/watch/watch.py", line 46, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/kadalu/lib/python3.8/site-packages/urllib3/response.py", line 793, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/kadalu/lib/python3.8/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

This looks like the issue which is happening. Will revert back after checking.

**Comment by amarts** [comment]
ok. One question. Is port 24007 under any firewall in OpenShift? If yes, please open it up. Specially on the nodes where you are having storage pods running.

**Comment by rmey** [comment]
@amarts port 24007 is not blocked anymore. I added a calico policy which opened the port for tcp/udp. A new error from today is in the gist.
https://gist.github.com/rmey/6f162e2269c19f31fc2e096694aea51c#file-2021-06-24-log
```
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: open24007
spec:
  selector: ibm.role == 'worker_public'
  ingress:
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 24007
  - action: Allow
    protocol: UDP
    destination:
      ports:
      - 24007
  order: 1500
```

**Comment by leelavg** [comment]
- After going through the log, I strongly believe this is coming from python kubernetes api [watching](https://github.com/kadalu/kadalu/blob/devel/operator/main.py#L844) the CRD and found below when I investigated along that route
- Out of all searches [this](https://github.com/emissary-ingress/emissary/pull/724) seems to fit well and so I think no other way than catching the error (maybe `urllib3.exceptions.InvalidChunkLength` rather than `ProtocolError` not to be broad, either ways that's implementation detail)
- However, this begs the question why now all of a sudden and can only think of two reasons.
1. Maybe we didn't test enough on OpenShift (Edit: in recent times?)
2. Maybe Kubernetes API itself changed and we are still installing `kubernetes==11.0.0`

**Comment by leelavg** [comment]
Btw, just deployed devel branch to check on the things and it looks good to me and no error in operator log as well

```
# k get pv,pvc; echo; k logs pod1                                                                                                                                                                                 
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM          STORAGECLASS      REASON   AGE
persistentvolume/pvc-da91b1de-3aae-4ddc-862d-fe2299061cc9   2Gi        RWX            Delete           Bound    kadalu/pvc2g   kadalu.replica1            3m44s

NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
persistentvolumeclaim/pvc2g   Bound    pvc-da91b1de-3aae-4ddc-862d-fe2299061cc9   2Gi        RWX            kadalu.replica1   3m45s

This is a sample application
# df -h
Filesystem                Size      Used Available Use% Mounted on
kadalu:replica1-pool      2.0G         0      2.0G   0% /mnt/pv
# mount
kadalu:replica1-pool on /mnt/pv type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
Write/Read test on PV mount
Thu Jun 24 13:56:16 UTC 2021
SUCCESS
```

**Comment by leelavg** [comment]
- PR #588 catches the exception and operator shouldn't restart every now and then
> The replication does not work - every of the 3 example pods which share a RWX PVC with replica3 mode storage class are looking like as they would have their own volume

- However, after this fix need to observe whether above issue also get resolved or not

**Comment by rmey** [comment]
I will try at the end of week with development branch using same environment

**Comment by leelavg** [comment]
@rmey ack,
- since #588 is merged, cleanup the namespace using [this](https://raw.githubusercontent.com/kadalu/kadalu/devel/extras/scripts/cleanup) script [please verify before running it]
- After cleanup, you can apply manifest for [openshift](https://raw.githubusercontent.com/kadalu/kadalu/devel/manifests/kadalu-operator-openshift.yaml) from devel branch
- Please note, the fix just suppresses exception and stops operator restarts however need to see the second part is fixed or not
