### ISSUE TITLE
Kadalu 0.8.4 release fails to install on ARM64

### ISSUE THREAD

**Issue by heathharrelson** [kadalu/kadalu#611]
Installing the 0.8.4 release is failing on ARM64 (k3s on Raspberry PI 4). After running `kubectl kadalu install` the operator goes into `CrashLoopBackOff` and logs the following:

```
λ kubectl -n kadalu logs operator-56898988c5-jw8v2
Traceback (most recent call last):
  File "/kadalu/start.py", line 3, in <module>
    from kadalulib import Monitor, Proc, logging_setup
  File "/kadalu/kadalulib.py", line 11, in <module>
    import xxhash
ModuleNotFoundError: No module named 'xxhash'
```

The 0.8.3 release seems to install successfully.

## Installation Details

```
λ ./kubectl-kadalu version
kubectl-kadalu 0.8.4
λ kubectl kadalu install
Executing 'kubectl apply -f https://github.com/kadalu/kadalu/releases/download/0.8.4/kadalu-operator.yaml'
Kadalu operator create request sent successfully
namespace/kadalu created
serviceaccount/kadalu-operator created
serviceaccount/kadalu-csi-nodeplugin created
serviceaccount/kadalu-csi-provisioner created
serviceaccount/kadalu-server-sa created
customresourcedefinition.apiextensions.k8s.io/kadalustorages.kadalu-operator.storage created
clusterrole.rbac.authorization.k8s.io/pod-exec unchanged
clusterrole.rbac.authorization.k8s.io/kadalu-operator unchanged
clusterrolebinding.rbac.authorization.k8s.io/kadalu-operator unchanged
deployment.apps/operator created
λ kubectl -n kadalu get pods
NAME                        READY   STATUS             RESTARTS   AGE
operator-56898988c5-jw8v2   0/1     CrashLoopBackOff   7          16m
λ kubectl -n kadalu describe pod operator-56898988c5-jw8v2
Name:         operator-56898988c5-jw8v2
Namespace:    kadalu
Priority:     0
Node:         k8snode1/192.168.4.43
Start Time:   Tue, 03 Aug 2021 18:18:11 -0700
Labels:       name=kadalu
              pod-template-hash=56898988c5
Annotations:  <none>
Status:       Running
IP:           10.42.1.6
IPs:
  IP:           10.42.1.6
Controlled By:  ReplicaSet/operator-56898988c5
Containers:
  kadalu-operator:
    Container ID:   containerd://406ca98aeff9a1ecf58af7e7eed434775b10210462b11b231e5b56fb759c1225
    Image:          docker.io/kadalu/kadalu-operator:0.8.4
    Image ID:       docker.io/kadalu/kadalu-operator@sha256:596aac1750d87e2c5cc8f4cfa1f74ad0b0c9007be110c3d0d112f3efbe7dc5e4
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 03 Aug 2021 18:35:00 -0700
      Finished:     Tue, 03 Aug 2021 18:35:00 -0700
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 03 Aug 2021 18:29:55 -0700
      Finished:     Tue, 03 Aug 2021 18:29:55 -0700
    Ready:          False
    Restart Count:  8
    Environment:
      WATCH_NAMESPACE:   kadalu (v1:metadata.namespace)
      POD_NAME:          operator-56898988c5-jw8v2 (v1:metadata.name)
      OPERATOR_NAME:     kadalu-operator
      DOCKER_USER:       kadalu
      KADALU_VERSION:    0.8.4
      KADALU_NAMESPACE:  kadalu
      KUBELET_DIR:       /var/lib/kubelet
      K8S_DIST:          kubernetes
      VERBOSE:           no
      DEPLOY_SOCAT:      no
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jrzbj (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-jrzbj:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  16m                  default-scheduler  Successfully assigned kadalu/operator-56898988c5-jw8v2 to k8snode1
  Normal   Pulling    16m                  kubelet            Pulling image "docker.io/kadalu/kadalu-operator:0.8.4"
  Normal   Pulled     16m                  kubelet            Successfully pulled image "docker.io/kadalu/kadalu-operator:0.8.4" in 23.960948961s
  Normal   Pulled     14m (x4 over 16m)    kubelet            Container image "docker.io/kadalu/kadalu-operator:0.8.4" already present on machine
  Normal   Created    14m (x5 over 16m)    kubelet            Created container kadalu-operator
  Normal   Started    14m (x5 over 16m)    kubelet            Started container kadalu-operator
  Warning  BackOff    115s (x68 over 16m)  kubelet            Back-off restarting failed container
λ kubectl -n kadalu logs operator-56898988c5-jw8v2
Traceback (most recent call last):
  File "/kadalu/start.py", line 3, in <module>
    from kadalulib import Monitor, Proc, logging_setup
  File "/kadalu/kadalulib.py", line 11, in <module>
    import xxhash
ModuleNotFoundError: No module named 'xxhash'
```

## Environment

Cluster is 4x Raspberry Pi 4, Ubuntu 20.04.2 LTS, k3s 1.21.3+k3s1.

```
λ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3+k3s1", GitCommit:"1d1f220fbee9cdeb5416b76b707dde8c231121f2", GitTreeState:"clean", BuildDate:"2021-07-22T20:46:24Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/arm64"}
λ kubectl get nodes
NAME        STATUS   ROLES                  AGE     VERSION
k8snode3    Ready    <none>                 3d23h   v1.21.3+k3s1
k8snode2    Ready    <none>                 3d23h   v1.21.3+k3s1
k8snode1    Ready    <none>                 3d23h   v1.21.3+k3s1
k8smaster   Ready    control-plane,master   3d23h   v1.21.3+k3s1
```

**Comment by leelavg** [comment]
@heathharrelson thanks for the report

@amarts when this was regressed earlier, what changes did you made?

Below is from aws arm:
```
-> docker run -it --entrypoint=/bin/bash kadalu/kadalu-operator:0.8.3
root@1bfc8fe20bef:/# python -c 'import xxhash'
root@1bfc8fe20bef:/# exit
-> docker run -it --entrypoint=/bin/bash kadalu/kadalu-operator:0.8.4
root@ed9d9a8cd00d:/# python -c 'import xxhash'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'xxhash'
root@ed9d9a8cd00d:/# exit
```
- I can only think of #592 but that's working in amd64 😕 
- Small query, we are using only `devel` branch for all builds right (like `arm` and `arm_test` are stale)?

**Comment by amarts** [comment]
> Small query, we are using only devel branch for all builds right (like arm and arm_test are stale)?

Yes, only devel branch (for the releases).

Not sure what changed yet. Will need to check again.
