### ISSUE TITLE
 kubectl kadalu  storage-remove fails

### ISSUE THREAD

**Issue by kotnn** [kadalu/kadalu#644]
Hello.
I've deployed kadalu to my on-prem cluster based on Vmware Vms and Ubuntu 20.04 as nodes.
Kadalu was deployed, storage was added, all pods are alive and no errors in log until i try to remove storage.
2 polls were created: pool1 and pool2. Working with pool2 now.
It was deployed with:
`kubectl kadalu storage-add pool2 --type=Replica1 --device k8snode02:/dev/sdc`
Trying do remive with ` kubectl kadalu  storage-remove pool2`
Output says pool deleted, but it is not true:
![image](https://user-images.githubusercontent.com/38759038/131880313-bc2f918d-3c69-45b3-aaac-9b5ec1d6d683.png)
All objects are in place:
![image](https://user-images.githubusercontent.com/38759038/131880547-f0c931e9-170e-4370-9780-cf650b466385.png)

but see strange error in logs:
[2021-09-02 15:53:38,088] ERROR [main - 737:get_num_pvs] - Failed to get size details of the storage "pool2"     error=error 1 error: You must be logged in to the server (Unauthorized)
[2021-09-02 15:53:38,088] ERROR [main - 634:handle_deleted] - Storage delete failed. Failed to get PV count      number_of_pvs=-1 storage=pool2
[2021-09-02 16:08:49,131] INFO [main - 629:handle_deleted] - Delete requested    volname=pool2
[2021-09-02 16:08:49,230] ERROR [main - 737:get_num_pvs] - Failed to get size details of the storage "pool2"     error=error 1 error: You must be logged in to the server (Unauthorized)
[2021-09-02 16:08:49,230] ERROR [main - 634:handle_deleted] - Storage delete failed. Failed to get PV count      number_of_pvs=-1 storage=pool2
[2021-09-02 16:17:38,991] INFO [main - 629:handle_deleted] - Delete requested    volname=pool2

**Comment by vatsa287** [comment]
Hi,
Could you please share operator logs and also 'kubectl get svc -nkadalu'

**Comment by leelavg** [comment]
@kotnn 

- Can you please look into / provide operator logs?
- You might've tried removing a pool which has PVC and there are some more corner cases
- Basically, it's usual when custom resources are deleted and k8s couldn't validate custom controllers ( in this case operator handle this operation)

**Comment by kotnn** [comment]
[logs.txt](https://github.com/kadalu/kadalu/files/7100361/logs.txt)
logs are attached
 'kubectl get svc -nkadalu' output:
![image](https://user-images.githubusercontent.com/38759038/131881641-f86cef30-7d8c-4613-a879-744602cae6b6.png)

**Comment by leelavg** [comment]
> [2021-09-02 15:53:38,088] ERROR [main - 737:get_num_pvs] - Failed to get size details of the storage "pool2" error=error 1 error: You must be logged in to the server (Unauthorized)

Yep, indeed this is strange, operator has all necessary permissions.

@vatsa287 leaving it to you.

**Comment by kotnn** [comment]
also storage still listed with  "kubectl-kadalu storage-list --detail" command:
![image](https://user-images.githubusercontent.com/38759038/131882980-45aef108-0f92-4464-8857-30d6b2bd04aa.png)
@vatsa287, @leelavg  thank you so much for quick response!

**Comment by kotnn** [comment]
[2021-09-02 17:36:33,677] INFO [main - 275:upgrade_storage_pods] - config map    volname=pool1 data={'namespace': 'kadalu', 'kadalu_version': '0.8.5', 'volname': 'pool1', 'volume_id': 'f37005e0-0bfd-11ec-aff9-1a0e36dc9828', 'kadalu_format': 'native', 'type': 'Replica3', 'pvReclaimPolicy': 'delete', 'bricks': [{'brick_path': '/bricks/pool1/data/brick', 'kube_hostname': 'k8snode01', 'node': 'server-pool1-0-0.pool1', 'node_id': 'node-0', 'host_brick_path': '', 'brick_device': '/dev/sdb', 'pvc_name': '', 'brick_device_dir': '', 'decommissioned': '', 'brick_index': 0}, {'brick_path': '/bricks/pool1/data/brick', 'kube_hostname': 'k8snode01', 'node': 'server-pool1-1-0.pool1', 'node_id': 'node-1', 'host_brick_path': '', 'brick_device': '/dev/sdc', 'pvc_name': '', 'brick_device_dir': '', 'decommissioned': '', 'brick_index': 1}, {'brick_path': '/bricks/pool1/data/brick', 'kube_hostname': 'k8snode02', 'node': 'server-pool1-2-0.pool1', 'node_id': 'node-2', 'host_brick_path': '', 'brick_device': '/dev/sdb', 'pvc_name': '', 'brick_device_dir': '', 'decommissioned': '', 'brick_index': 2}], 'disperse': {'data': 0, 'redundancy': 0}, 'options': {}}
[2021-09-02 17:36:33,678] INFO [main - 232:get_brick_device_dir] - {'node_id': 'node-0', 'path': '', 'node': 'k8snode01', 'device': '/dev/sdb', 'pvc': ''}
[2021-09-02 17:36:33,678] INFO [main - 234:get_brick_device_dir] - /dev/sdb
Traceback (most recent call last):
  File "/kadalu/main.py", line 1019, in <module>
    main()
  File "/kadalu/main.py", line 999, in main
    upgrade_storage_pods(core_v1_client)
  File "/kadalu/main.py", line 324, in upgrade_storage_pods
    deploy_server_pods(obj)
  File "/kadalu/main.py", line 446, in deploy_server_pods
    lib_execute(KUBECTL_CMD, APPLY_CMD, "-f", filename)
  File "/kadalu/kadalulib.py", line 153, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  error: You must be logged in to the server (the server has asked for the client to provide credentials)
[2021-09-02 17:36:34,213] INFO [kadalulib - 402:monitor_proc] - Restarted Process        name=operator
[2021-09-02 17:36:34,711] INFO [main - 926:deploy_config_map] - Found existing configmap. Updating       name=kadalu-info
[2021-09-02 17:36:34,720] INFO [main - 948:deploy_config_map] - ConfigMap Deployed       manifest=/kadalu/templates/configmap.yaml uid=1fe8270a-bda5-4d26-bff7-ceab8cee7d9c upgrade=True
[2021-09-02 17:36:35,494] INFO [main - 914:deploy_csi_pods] - Deployed CSI Pods  manifest=/kadalu/templates/csi.yaml
[2021-09-02 17:36:35,495] INFO [main - 998:main] - Upgrading to          version=0.8.5
[2021-09-02 17:36:35,504] INFO [main - 275:upgrade_storage_pods] - config map    volname=pool1 data={'namespace': 'kadalu', 'kadalu_version': '0.8.5', 'volname': 'pool1', 'volume_id': 'f37005e0-0bfd-11ec-aff9-1a0e36dc9828', 'kadalu_format': 'native', 'type': 'Replica3', 'pvReclaimPolicy': 'delete', 'bricks': [{'brick_path': '/bricks/pool1/data/brick', 'kube_hostname': 'k8snode01', 'node': 'server-pool1-0-0.pool1', 'node_id': 'node-0', 'host_brick_path': '', 'brick_device': '/dev/sdb', 'pvc_name': '', 'brick_device_dir': '', 'decommissioned': '', 'brick_index': 0}, {'brick_path': '/bricks/pool1/data/brick', 'kube_hostname': 'k8snode01', 'node': 'server-pool1-1-0.pool1', 'node_id': 'node-1', 'host_brick_path': '', 'brick_device': '/dev/sdc', 'pvc_name': '', 'brick_device_dir': '', 'decommissioned': '', 'brick_index': 1}, {'brick_path': '/bricks/pool1/data/brick', 'kube_hostname': 'k8snode02', 'node': 'server-pool1-2-0.pool1', 'node_id': 'node-2', 'host_brick_path': '', 'brick_device': '/dev/sdb', 'pvc_name': '', 'brick_device_dir': '', 'decommissioned': '', 'brick_index': 2}], 'disperse': {'data': 0, 'redundancy': 0}, 'options': {}}
[2021-09-02 17:36:35,504] INFO [main - 232:get_brick_device_dir] - {'node_id': 'node-0', 'path': '', 'node': 'k8snode01', 'device': '/dev/sdb', 'pvc': ''}
[2021-09-02 17:36:35,504] INFO [main - 234:get_brick_device_dir] - /dev/sdb
[2021-09-02 17:36:35,950] INFO [main - 447:deploy_server_pods] - Deployed Server pod     volname=pool1 manifest=/kadalu/templates/server.yaml node=k8snode01
[2021-09-02 17:36:35,950] INFO [main - 232:get_brick_device_dir] - {'node_id': 'node-1', 'path': '', 'node': 'k8snode01', 'device': '/dev/sdc', 'pvc': ''}
[2021-09-02 17:36:35,951] INFO [main - 234:get_brick_device_dir] - /dev/sdc
Traceback (most recent call last):
  File "/kadalu/main.py", line 1019, in <module>
    main()
  File "/kadalu/main.py", line 999, in main
    upgrade_storage_pods(core_v1_client)
  File "/kadalu/main.py", line 324, in upgrade_storage_pods
    deploy_server_pods(obj)
  File "/kadalu/main.py", line 446, in deploy_server_pods
    lib_execute(KUBECTL_CMD, APPLY_CMD, "-f", filename)
  File "/kadalu/kadalulib.py", line 153, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  error: You must be logged in to the server (the server has asked for the client to provide credentials)
[2021-09-02 17:36:36,218] INFO [kadalulib - 402:monitor_proc] - Restarted Process        name=operator
[2021-09-02 17:36:36,701] INFO [main - 926:deploy_config_map] - Found existing configmap. Updating       name=kadalu-info
[2021-09-02 17:36:36,709] INFO [main - 948:deploy_config_map] - ConfigMap Deployed       manifest=/kadalu/templates/configmap.yaml uid=1fe8270a-bda5-4d26-bff7-ceab8cee7d9c upgrade=True
[2021-09-02 17:36:37,449] INFO [main - 914:deploy_csi_pods] - Deployed CSI Pods  manifest=/kadalu/templates/csi.yaml
[2021-09-02 17:36:37,450] INFO [main - 998:main] - Upgrading to          version=0.8.5
[2021-09-02 17:36:37,459] INFO [main - 275:upgrade_storage_pods] - config map    volname=pool1 data={'namespace': 'kadalu', 'kadalu_version': '0.8.5', 'volname': 'pool1', 'volume_id': 'f37005e0-0bfd-11ec-aff9-1a0e36dc9828', 'kadalu_format': 'native', 'type': 'Replica3', 'pvReclaimPolicy': 'delete', 'bricks': [{'brick_path': '/bricks/pool1/data/brick', 'kube_hostname': 'k8snode01', 'node': 'server-pool1-0-0.pool1', 'node_id': 'node-0', 'host_brick_path': '', 'brick_device': '/dev/sdb', 'pvc_name': '', 'brick_device_dir': '', 'decommissioned': '', 'brick_index': 0}, {'brick_path': '/bricks/pool1/data/brick', 'kube_hostname': 'k8snode01', 'node': 'server-pool1-1-0.pool1', 'node_id': 'node-1', 'host_brick_path': '', 'brick_device': '/dev/sdc', 'pvc_name': '', 'brick_device_dir': '', 'decommissioned': '', 'brick_index': 1}, {'brick_path': '/bricks/pool1/data/brick', 'kube_hostname': 'k8snode02', 'node': 'server-pool1-2-0.pool1', 'node_id': 'node-2', 'host_brick_path': '', 'brick_device': '/dev/sdb', 'pvc_name': '', 'brick_device_dir': '', 'decommissioned': '', 'brick_index': 2}], 'disperse': {'data': 0, 'redundancy': 0}, 'options': {}

**Comment by kotnn** [comment]
so I found a cause:
![image](https://user-images.githubusercontent.com/38759038/131909583-592a8cf9-51fe-4f43-a4f8-543dc3fb34d4.png)
operator cannot exec dbquery due to unauthorized error. Other commands like  "ls", "whoami" are working
But still dont know how to fix this

**Comment by leelavg** [comment]
> error: You must be logged in to the server (the server has asked for the client to provide credentials)

RBAC and service accounts were working fine the last time I checked.

Maybe some version changes, can you please provide kadalu, kubectl (client and server) versions?

**Comment by kotnn** [comment]
![image](https://user-images.githubusercontent.com/38759038/131959604-9efc5b86-37aa-43c7-895b-33a038299d46.png)

**Comment by kotnn** [comment]
the issue resolved by adding:
  resources:
  - pods/exec
  - pods/log
![image](https://user-images.githubusercontent.com/38759038/131962708-c37b662b-087c-439f-b263-fd17fa0082ae.png)
in clusterrole "kadalu-operator"
and restarting kadalu-operator pod.
Not sure if pod restart required as well as adding "pod/log" to role. Did all operations in bunch. Do not want to touch anything anymore because it works :)

fresh logs: 
[2021-09-03 06:44:33,081] INFO [main - 629:handle_deleted] - Delete requested    volname=pool2
[2021-09-03 06:44:33,511] INFO [main - 833:delete_storage_class] - Deleted Storage class         volname=pool2
[2021-09-03 06:44:33,555] INFO [main - 819:delete_config_map] - Deleted configmap        name=kadalu-info volname=pool2
[2021-09-03 06:44:33,671] INFO [main - 795:delete_server_pods] - Deleted Server pod      volname=pool2 manifest=/kadalu/templates/server.yaml node=server-pool2-0-0.pool2
[2021-09-03 06:44:33,820] INFO [main - 662:handle_deleted] - Deleted Service     volname=pool2 manifest=/kadalu/templates/services.yaml

also we see pool2-related objects dissappear:
![image](https://user-images.githubusercontent.com/38759038/131968710-bc452c46-7799-47a0-bc6a-2360a73c12e8.png)

**Comment by leelavg** [comment]
- I use v1.21.2-k3s1 and CI uses v1.20-k8s but didn't hit this
- Nevertheless, thanks for looking into it and providing the solution
- Will need an update here https://github.com/kadalu/kadalu/blob/382c527ea4e836d3e088ba17da79a94a65a24fea/templates/operator.yaml.j2#L169-L171
- Just referring https://github.com/kadalu/kadalu/issues/601 here to have this fixed as well

**Comment by vatsa287** [comment]
Pretty strange, I was able to delete in my setup,
```
vatsa@thinkpad:~/kadalu$ kubectl kadalu storage-remove storage-pool-1
Storage Yaml file for your reference:

apiVersion: "kadalu-operator.storage/v1alpha1"
kind: "KadaluStorage"
metadata:
  name: "storage-pool-1"

Is this correct?(Yes/No): y
Storage delete request sent successfully.

kadalustorage.kadalu-operator.storage "storage-pool-1" deleted


vatsa@thinkpad:~/kadalu$ kubectl logs -nkadalu deploy/operator
[2021-09-03 07:24:55,140] INFO [kadalulib - 367:start_all] - Started Process	 name=operator
[2021-09-03 07:24:55,142] INFO [kadalulib - 367:start_all] - Started Process	 name=metrics
[2021-09-03 07:25:13,618] INFO [main - 948:deploy_config_map] - ConfigMap Deployed	 manifest=/kadalu/templates/configmap.yaml uid=95456e0f-7938-4f28-81cb-93531ed6c407 upgrade=False
[2021-09-03 07:25:18,456] INFO [main - 914:deploy_csi_pods] - Deployed CSI Pods	 manifest=/kadalu/templates/csi.yaml
[2021-09-03 07:26:15,675] INFO [main - 976:deploy_storage_class] - Deployed StorageClass	 manifest=/kadalu/templates/storageclass-kadalu.custom.yaml
[2021-09-03 07:26:15,685] INFO [main - 232:get_brick_device_dir] - {'node': 'thinkpad', 'path': '/mnt/disk1', 'node_id': 'node-0'}
[2021-09-03 07:26:15,685] INFO [main - 234:get_brick_device_dir] - 
[2021-09-03 07:26:15,688] INFO [main - 394:update_config_map] - Updated configmap	 name=kadalu-info volname=storage-pool-1
[2021-09-03 07:26:15,689] INFO [main - 232:get_brick_device_dir] - {'node': 'thinkpad', 'path': '/mnt/disk1', 'node_id': 'node-0'}
[2021-09-03 07:26:15,689] INFO [main - 234:get_brick_device_dir] - 
[2021-09-03 07:26:16,426] INFO [main - 447:deploy_server_pods] - Deployed Server pod	 volname=storage-pool-1 manifest=/kadalu/templates/server.yaml node=thinkpad
[2021-09-03 07:26:18,433] INFO [main - 559:handle_added] - Deployed Service	 volname=storage-pool-1 manifest=/kadalu/templates/services.yaml
[2021-09-03 07:27:34,945] INFO [main - 629:handle_deleted] - Delete requested	 volname=storage-pool-1
[2021-09-03 07:27:36,088] INFO [main - 833:delete_storage_class] - Deleted Storage class	 volname=storage-pool-1
[2021-09-03 07:27:36,112] INFO [main - 819:delete_config_map] - Deleted configmap	 name=kadalu-info volname=storage-pool-1
[2021-09-03 07:27:37,206] INFO [main - 795:delete_server_pods] - Deleted Server pod	 volname=storage-pool-1 manifest=/kadalu/templates/server.yaml node=server-storage-pool-1-0-0.storage-pool-1
[2021-09-03 07:27:38,075] INFO [main - 662:handle_deleted] - Deleted Service	 volname=storage-pool-1 manifest=/kadalu/templates/services.yaml


vatsa@thinkpad:~/kadalu$ kubectl get pods -nkadalu
NAME                          READY   STATUS        RESTARTS   AGE
kadalu-csi-nodeplugin-bkrd2   3/3     Running       0          2m48s
kadalu-csi-provisioner-0      5/5     Running       0          2m28s
operator-65b5c8cb49-j5qtc     1/1     Running       0          2m59s
server-storage-pool-1-0-0     0/1     Terminating   0          89s

vatsa@thinkpad:~/kadalu$ kubectl get pods -nkadalu
NAME                          READY   STATUS    RESTARTS   AGE
kadalu-csi-nodeplugin-bkrd2   3/3     Running   0          3m11s
kadalu-csi-provisioner-0      5/5     Running   0          2m51s
operator-65b5c8cb49-j5qtc     1/1     Running   0          3m22s
```
