### ISSUE TITLE
kadalulib.CommandException: [1]  error: unable to recognize "/kadalu/templates/csi-driver-object.yaml": no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by hunter86bg** [kadalu/kadalu#681]
It seems that latest manifests traceback with :
```
[2021-10-28 22:23:52,759] INFO [main - 948:deploy_config_map] - ConfigMap Deployed	 manifest=/kadalu/templates/configmap.yaml uid=6486d6d1-48b1-42c1-8794-5a2ed1840f91 upgrade=True
Traceback (most recent call last):
  File "/kadalu/main.py", line 1019, in <module>
    main()
  File "/kadalu/main.py", line 995, in main
    deploy_csi_pods(core_v1_client)
  File "/kadalu/main.py", line 901, in deploy_csi_pods
    lib_execute(KUBECTL_CMD, APPLY_CMD, "-f", filename)
  File "/kadalu/kadalulib.py", line 154, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  error: unable to recognize "/kadalu/templates/csi-driver-object.yaml": no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta1"
[2021-10-28 22:23:54,277] INFO [kadalulib - 403:monitor_proc] - Restarted Process	 name=operator
[2021-10-28 22:23:54,692] INFO [main - 926:deploy_config_map] - Found existing configmap. Updating	 name=kadalu-info
[2021-10-28 22:23:54,700] INFO [main - 948:deploy_config_map] - ConfigMap Deployed	 manifest=/kadalu/templates/configmap.yaml uid=6486d6d1-48b1-42c1-8794-5a2ed1840f91 upgrade=True
Traceback (most recent call last):
  File "/kadalu/main.py", line 1019, in <module>
    main()
  File "/kadalu/main.py", line 995, in main
    deploy_csi_pods(core_v1_client)
  File "/kadalu/main.py", line 901, in deploy_csi_pods
    lib_execute(KUBECTL_CMD, APPLY_CMD, "-f", filename)
  File "/kadalu/kadalulib.py", line 154, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  error: unable to recognize "/kadalu/templates/csi-driver-object.yaml": no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta1"
[2021-10-28 22:23:56,281] INFO [kadalulib - 403:monitor_proc] - Restarted Process	 name=operator
[2021-10-28 22:23:56,686] INFO [main - 926:deploy_config_map] - Found existing configmap. Updating	 name=kadalu-info
[2021-10-28 22:23:56,693] INFO [main - 948:deploy_config_map] - ConfigMap Deployed	 manifest=/kadalu/templates/configmap.yaml uid=6486d6d1-48b1-42c1-8794-5a2ed1840f91 upgrade=True
Traceback (most recent call last):
  File "/kadalu/main.py", line 1019, in <module>
    main()
  File "/kadalu/main.py", line 995, in main
    deploy_csi_pods(core_v1_client)
  File "/kadalu/main.py", line 901, in deploy_csi_pods
    lib_execute(KUBECTL_CMD, APPLY_CMD, "-f", filename)
  File "/kadalu/kadalulib.py", line 154, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  error: unable to recognize "/kadalu/templates/csi-driver-object.yaml": no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta1"
[2021-10-28 22:23:58,285] INFO [kadalulib - 403:monitor_proc] - Restarted Process	 name=operator
[2021-10-28 22:23:58,693] INFO [main - 926:deploy_config_map] - Found existing configmap. Updating	 name=kadalu-info
[2021-10-28 22:23:58,699] INFO [main - 948:deploy_config_map] - ConfigMap Deployed	 manifest=/kadalu/templates/configmap.yaml uid=6486d6d1-48b1-42c1-8794-5a2ed1840f91 upgrade=True
Traceback (most recent call last):
  File "/kadalu/main.py", line 1019, in <module>
    main()
  File "/kadalu/main.py", line 995, in main
    deploy_csi_pods(core_v1_client)
  File "/kadalu/main.py", line 901, in deploy_csi_pods
    lib_execute(KUBECTL_CMD, APPLY_CMD, "-f", filename)
  File "/kadalu/kadalulib.py", line 154, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  error: unable to recognize "/kadalu/templates/csi-driver-object.yaml": no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta1"
```

**Comment by leelavg** [comment]
@hunter86bg 

- it seems your k8s version >= 1.22 but your local repo of kadalu doesn't contain commit #669 
- from above log, line 901 is `lib_execute` but it should be at line 904 for k8s version >= 1.22

Pls re-check.

**Comment by hunter86bg** [comment]
No Longer observed with 0.8.7
