### ISSUE TITLE
Collecting Metrics Issue

### ISSUE THREAD

**Issue by vherrlein** [kadalu/kadalu#706]
Dear team,

May be it's because my K3s is running under LXC/LXD containers.
However, since you fixed on the version 0.8.8 the metrics issue coming from the #687 it seems now another issue occurs from the operator exporter with the following message.

```shell
[2021-11-20 10:34:45,591] ERROR [httptools_impl - 378:run_asgi] - Exception in ASGI application
Traceback (most recent call last):
  File "/kadalu/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/kadalu/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/kadalu/exporter.py", line 369, in collect_metrics
    collect_and_set_prometheus_metrics()
  File "/kadalu/exporter.py", line 355, in collect_and_set_prometheus_metrics
    brick["node"].rstrip("."+storage["name"])).set(brick["memory_usage_in_bytes"])
KeyError: 'memory_usage_in_bytes'
```

https://github.com/kadalu/kadalu/blob/42b440bd8db8c4b1b6d6a839f778c969f464a2c3/operator/exporter.py#L355

So, it seems `memory_usage_in_bytes` and probably `cpu_usage_in_nanoseconds` keys are not available.

Would it be a good idea to make sure all metrics are gracefully catched in case of errors ?

Otherwise it will be almost impossible to grab the other metrics.

Thank you in advance.

Regards,

**Comment by vherrlein** [comment]
After testing, all of those pieces of code doesn't works:

```python
        for brick in storage["bricks"]:
            storage_metrics.memory_usage.labels(
                brick["node"].rstrip("."+storage["name"])).set(brick["memory_usage_in_bytes"])
            storage_metrics.cpu_usage.labels(
                brick["node"].rstrip("."+storage["name"])).set(brick["cpu_usage_in_nanoseconds"])

            storage_metrics.total_number_of_containers.labels(
                brick["node"].rstrip("."+storage["name"])).set(brick["total_number_of_containers"])
            storage_metrics.number_of_ready_containers.labels(
                brick["node"].rstrip("."+storage["name"])).set(brick["number_of_ready_containers"])
```

So may be something happening when the operator exporter tries to collect metrics from all pods...

**Comment by leelavg** [comment]
- #708 should have probably fixed this issue too, I'm closing this, pls re-open if you want to have this separate or let's communicate over #709 alone wrt any Metrics issue from you if they aren't deviating too much
