### ISSUE TITLE
Metrics - Missing 'import os' declaration

### ISSUE THREAD

**Issue by vherrlein** [kadalu/kadalu#707]
Issue within server/exporter.py.

It seems `import os` declaration is missing at the top.

```shell
[2021-11-21 18:02:45,610] ERROR [httptools_impl - 378:run_asgi] - Exception in ASGI application
Traceback (most recent call last):
  File "/kadalu/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/kadalu/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/kadalu/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/kadalu/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/kadalu/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/kadalu/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/kadalu/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/kadalu/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/kadalu/exporter.py", line 28, in metrics
    if os.path.exists(memory_usage_file_path):
NameError: name 'os' is not defined

```

https://github.com/kadalu/kadalu/blob/9c9625aba981948ffae868748f1f828531dc7266/server/exporter.py#L2

**Comment by leelavg** [comment]
Uh oh, how come pylint missed it, maybe due to disable statements 🤔

**Comment by vatsa287** [comment]
Indeed #706 looks like it happened because this error. Will bring exporter files under pylint for avoiding catching of these errors.
