### ISSUE TITLE
Cannot correctly remove `kadaluStorage` and pvc

### ISSUE THREAD

**Issue by scr1ble** [kadalu/kadalu#722]
Hi there, 

I'm trying to delete the `kadaluStorage` and create a new one but I always get different problems. 

If there is no pvc'c in the cluster and no kadaluStorage, I can see in the logs that it is trying to find them.

Nothing changes if I remove kadalu from the cluster and restart it.

Could you help me?  

That what I've got in the logs right now.
```
[2021-12-03 06:43:44.151682 +0000] W [fuse-bridge.c:4049:fuse_statfs_resume] 0-glusterfs-fuse: 772: STATFS (00000000-0000-0000-0000-000000000001) resolution fail
[2021-12-03 06:43:44.308539 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage1-client-0: DNS resolution failed on host server-storage1-0-0.storage1
[2021-12-03 06:43:45.489846 +0000] W [fuse-resolve.c:125:fuse_resolve_gfid_cbk] 0-fuse: 00000000-0000-0000-0000-000000000001: failed to resolve (Transport endpoint is not connected)
[2021-12-03 06:43:45.489896 +0000] W [fuse-bridge.c:4049:fuse_statfs_resume] 0-glusterfs-fuse: 774: STATFS (00000000-0000-0000-0000-000000000001) resolution fail
[2021-12-03 06:43:46.153980 +0000] W [fuse-resolve.c:125:fuse_resolve_gfid_cbk] 0-fuse: 00000000-0000-0000-0000-000000000001: failed to resolve (Transport endpoint is not connected)
[2021-12-03 06:43:46.154015 +0000] W [fuse-bridge.c:4049:fuse_statfs_resume] 0-glusterfs-fuse: 776: STATFS (00000000-0000-0000-0000-000000000001) resolution fail
[2021-12-03 06:43:47.317284 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage1-client-0: DNS resolution failed on host server-storage1-0-0.storage1
[2021-12-03 06:43:47.492159 +0000] W [fuse-resolve.c:125:fuse_resolve_gfid_cbk] 0-fuse: 00000000-0000-0000-0000-000000000001: failed to resolve (Transport endpoint is not connected)
[2021-12-03 06:43:47.492202 +0000] W [fuse-bridge.c:4049:fuse_statfs_resume] 0-glusterfs-fuse: 778: STATFS (00000000-0000-0000-0000-000000000001) resolution fail
[2021-12-03 06:43:48.156346 +0000] W [fuse-resolve.c:125:fuse_resolve_gfid_cbk] 0-fuse: 00000000-0000-0000-0000-000000000001: failed to resolve (Transport endpoint is not connected)
[2021-12-03 06:43:48.156381 +0000] W [fuse-bridge.c:4049:fuse_statfs_resume] 0-glusterfs-fuse: 780: STATFS (00000000-0000-0000-0000-000000000001) resolution fail
[2021-12-03 06:43:48.759515 +0000] W [fuse-bridge.c:1415:fuse_attr_cbk] 0-glusterfs-fuse: 390: LOOKUP() / => -1 (Transport endpoint is not connected)
[2021-12-03 06:43:48.764880 +0000] W [fuse-bridge.c:1415:fuse_attr_cbk] 0-glusterfs-fuse: 391: LOOKUP() / => -1 (Transport endpoint is not connected)
[2021-12-03 06:43:48.815517 +0000] W [fuse-bridge.c:1981:fuse_err_cbk] 0-glusterfs-fuse: 4022: SETXATTR() /subvol/80/c5/pvc-75149ce2-65e9-4901-b94a-b955e6406284 => -1 (Operation not supported)
[2021-12-03 06:43:48.826067 +0000] W [fuse-bridge.c:1981:fuse_err_cbk] 0-glusterfs-fuse: 4029: SETXATTR() /subvol/b0/8d/pvc-aec97a02-5f7f-423c-aba2-2be0cfce7a10 => -1 (Operation not supported)
[2021-12-03 06:43:48.837187 +0000] W [fuse-bridge.c:1981:fuse_err_cbk] 0-glusterfs-fuse: 1964: SETXATTR() /subvol/80/c5/pvc-75149ce2-65e9-4901-b94a-b955e6406284 => -1 (Operation not supported)
[2021-12-03 06:43:48.848524 +0000] W [fuse-bridge.c:1981:fuse_err_cbk] 0-glusterfs-fuse: 1971: SETXATTR() /subvol/b0/8d/pvc-aec97a02-5f7f-423c-aba2-2be0cfce7a10 => -1 (Operation not supported)
[2021-12-03 06:43:48.858330 +0000] W [fuse-bridge.c:1981:fuse_err_cbk] 0-glusterfs-fuse: 4047: SETXATTR() /subvol/80/c5/pvc-75149ce2-65e9-4901-b94a-b955e6406284 => -1 (Operation not supported)
[2021-12-03 06:43:48.869178 +0000] W [fuse-bridge.c:1981:fuse_err_cbk] 0-glusterfs-fuse: 4054: SETXATTR() /subvol/b0/8d/pvc-aec97a02-5f7f-423c-aba2-2be0cfce7a10 => -1 (Operation not supported)
[2021-12-03 06:43:48.880680 +0000] W [fuse-bridge.c:1981:fuse_err_cbk] 0-glusterfs-fuse: 4021: SETXATTR() /subvol/80/c5/pvc-75149ce2-65e9-4901-b94a-b955e6406284 => -1 (Operation not supported)
[2021-12-03 06:43:48.891002 +0000] W [fuse-bridge.c:1981:fuse_err_cbk] 0-glusterfs-fuse: 4028: SETXATTR() /subvol/b0/8d/pvc-aec97a02-5f7f-423c-aba2-2be0cfce7a10 => -1 (Operation not supported)
```

**Comment by leelavg** [comment]
> that it is trying to find them

What does 'it' refers to?

> That what I've got in the logs right now

Which container logs are these?

If you want to clean the setup you can run https://github.com/kadalu/kadalu/blob/devel/extras/scripts/cleanup

- There are many unknowns in the report
1. What's the version?
2. Are tou trying to delete new storage or used(/in use) storage
3. How did you remove Kadalu from the cluster?

**Comment by scr1ble** [comment]
Hi,
> What does 'it' refers to?

It's about kadalu
> Which container logs are these?

Can't say for sure. Could you tell which one is using `glusterfs` binary for connection?

> 1. What's the version?
>2. Are tou trying to delete new storage or used(/in use) storage
>3. How did you remove Kadalu from the cluster?

1. 0.8.8 latest
2. I'm trying to delete already used storage.
3. It's installed with helm and cleaned with helm uninstall. Also I tried to remove it with this [instruction](https://github.com/kadalu/kadalu/blob/devel/extras/scripts/cleanup)

**Comment by leelavg** [comment]
> Could you tell which one is using glusterfs binary for connection?

sry, you might not like my answer on this, there are many containers where gluster logs the messages, if you are unaware where you pulled this logs from, leave it for now.

> I'm trying to delete already used storage.

I'm assuming it's internal gluster?

> It's installed with helm and cleaned with helm uninstall.

Ah! helm doesn't have knowledge of what operator manages so when you uninstall it just removes the operator and csi pods but not server pods

> Also I tried to remove it with this instruction

Then you shouldn't be having any issue after running the cleanup, it deletes the resources in kadalu namespace correctly.

I could only think either of these reasons, you might be ...
1. ... using same disk without cleaning it up and if you want to re-use disk with existing data, you need to re-use the volume-id from `getfattr -d -m . -e text <host_brick>`
2. ... using same external gluster volume without removing left out dirs, refer [cleanup](https://kadalu.io/docs/k8s-storage/devel/external-gluster-storage/) section

**Comment by scr1ble** [comment]
>I'm assuming it's internal gluster?

Oh, sorry my bad, I'm using external.

I'll try your recommendations.

Thanks a lot for your help!

**Comment by scr1ble** [comment]
Hi @leelavg,

So I've tried your recommendations and everything works as expected. Thanks again!

But if I delete kadaluStorage and trying to recreate it with the same name I see this
```
$ k delete storageclass kadalu.kadalu-storage-ext
storageclass.storage.k8s.io "kadalu.kadalu-storage-ext" deleted
$ k apply -f kadalu-storage-ext-gfs-delete.yaml
kadalustorage.kadalu-operator.storage/kadalu-storage-ext unchanged
```
But there is no any storage classes in my cluster
```
$ k get storageclass
No resources found
```
Could you help me with this? :)

**Comment by leelavg** [comment]
- what's the o/p of `k get po,sc,svc,kds,pv,pvc,cm -n kadalu`
- in-addition, if you can't provide all of above what does the operator logs say?
- if you are sure that no storage is in use either external or internal, run `k delete kds --all -nkadalu` and perform your operations

**Comment by scr1ble** [comment]
> * what's the o/p of k get po,sc,svc,kds,pv,pvc,cm -n kadalu
```
$ k get po,sc,svc,kds,pv,pvc,cm -n kadalu
NAME                              READY   STATUS    RESTARTS   AGE
pod/kadalu-csi-nodeplugin-5x6r9   3/3     Running   0          62m
pod/kadalu-csi-nodeplugin-lp5gf   3/3     Running   0          62m
pod/kadalu-csi-provisioner-0      5/5     Running   0          45m
pod/operator-79bfcd4bfd-9t7gl     1/1     Running   0          45m

NAME                         DATA   AGE
configmap/kadalu-info        4      62m
configmap/kube-root-ca.crt   1      62m
```
>* in-addition, if you can't provide all of above what does the operator logs say?
```
$ k logs -n kadalu operator-79bfcd4bfd-9t7gl --all-containers
[2021-12-08 05:41:14,275] INFO [kadalulib - 370:start_all] - Started Process	 name=operator
[2021-12-08 05:41:14,278] INFO [kadalulib - 370:start_all] - Started Process	 name=metrics
[2021-12-08 05:41:15,825] INFO [main - 936:deploy_config_map] - Found existing configmap. Updating	 name=kadalu-info
[2021-12-08 05:41:15,836] INFO [main - 958:deploy_config_map] - ConfigMap Deployed	 manifest=/kadalu/templates/configmap.yaml uid=a7f5409e-59df-475d-b1e8-83b11993ad1a upgrade=True
[2021-12-08 05:41:15,860] INFO [exporter - 385:<module>] - Started metrics exporter process at port 8050
INFO:     Started server process [10]
[2021-12-08 05:41:15,903] INFO [server - 84:serve] - Started server process [10]
INFO:     Waiting for application startup.
[2021-12-08 05:41:15,904] INFO [on - 45:startup] - Waiting for application startup.
INFO:     Application startup complete.
[2021-12-08 05:41:15,905] INFO [on - 59:startup] - Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8050 (Press CTRL+C to quit)
[2021-12-08 05:41:15,906] INFO [server - 217:_log_started_message] - Uvicorn running on http://0.0.0.0:8050 (Press CTRL+C to quit)
[2021-12-08 05:41:17,047] INFO [main - 924:deploy_csi_pods] - Deployed CSI Pods	 manifest=/kadalu/templates/csi.yaml
[2021-12-08 05:41:17,048] INFO [main - 1008:main] - Upgrading to 	 version=0.8.8
[2021-12-08 05:41:17,053] INFO [main - 277:upgrade_storage_pods] - config map	 volname=kadalu-storage-ext data={'volname': 'kadalu-storage-ext', 'volume_id': 'c908ed54-57e7-11ec-86bf-5e5448fb2947', 'type': 'External', 'pvReclaimPolicy': 'delete', 'kadalu_format': 'native', 'gluster_hosts': '192.168.2.4', 'gluster_volname': 'main', 'gluster_options': ''}
[2021-12-08 05:42:36,359] INFO [main - 489:handle_external_storage_addition] - Updated configmap	 name=kadalu-info volname=kadalu-storage-ext-0
[2021-12-08 05:42:36,708] INFO [main - 494:handle_external_storage_addition] - Deployed External StorageClass	 volname=kadalu-storage-ext-0 manifest=/kadalu/templates/external-storageclass.yaml
```
>* if you are sure that no storage is in use either external or internal, run k delete kds --all -nkadalu and perform your operations
```
$k delete kds --all -nkadalu
No resources found
```

**Comment by leelavg** [comment]
> [2021-12-08 05:42:36,708] INFO [main - 494:handle_external_storage_addition] - Deployed External StorageClass	 volname=kadalu-storage-ext-0 manifest=/kadalu/templates/external-storageclass.yaml

even after above line, you aren't able to see any `k get kds,sc`?

**Comment by scr1ble** [comment]
Oh, my bad again :( 
I've deleted all `kds` in my cluster right now and trying to recreate them.
`kds` is created but there is no `sc` and obviously that my `pvc` can't find it.

```
$ k delete kds --all
kadalustorage.kadalu-operator.storage "kadalu-storage-ext" deleted
kadalustorage.kadalu-operator.storage "kadalu-storage-ext-0" deleted

$ k apply -f kadalu-storage-ext-gfs-delete.yaml
kadalustorage.kadalu-operator.storage/kadalu-storage-ext-0 created

$ k get sc
No resources found

$ k get kds,sc
NAME                                                         AGE
kadalustorage.kadalu-operator.storage/kadalu-storage-ext-0   16s

$ k apply -f test-pvc-del.yaml
persistentvolumeclaim/test-pvc created
$ k describe pvc test-pvc -n appns
Name:          test-pvc
Namespace:     appns
StorageClass:  kadalu.kadalu-storage-ext-0
Status:        Pending
Volume:
Labels:        app=appns
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason              Age                From                         Message
  ----     ------              ----               ----                         -------
  Warning  ProvisioningFailed  13s (x4 over 44s)  persistentvolume-controller  storageclass.storage.k8s.io "kadalu.kadalu-storage-ext-0" not found

**Comment by leelavg** [comment]
- between below operations you see operator log stating storage class is deployed?
```
$ k apply -f kadalu-storage-ext-gfs-delete.yaml
kadalustorage.kadalu-operator.storage/kadalu-storage-ext-0 created

$ k get sc
No resources found
```
- less than a minute is very less time to confirm all internal knobs are turned correctly or not 😅

**Comment by scr1ble** [comment]
>between below operations you see operator log stating storage class is deployed?

This are the logs after deleting and creatint `kds`
Right now only kadalu-storage-ext-0 is created
```
[2021-12-08 07:59:10,358] INFO [main - 631:handle_deleted] - Delete requested	 volname=kadalu-storage-ext-0
Traceback (most recent call last):
  File "/kadalu/main.py", line 1029, in <module>
    main()
  File "/kadalu/main.py", line 1018, in main
    crd_watch(core_v1_client, k8s_client)
  File "/kadalu/main.py", line 875, in crd_watch
    watch_stream(core_v1_client, k8s_client)
  File "/kadalu/main.py", line 866, in watch_stream
    handle_deleted(core_v1_client, obj)
  File "/kadalu/main.py", line 655, in handle_deleted
    delete_storage_class(volname, hostvol_type)
  File "/kadalu/main.py", line 834, in delete_storage_class
    lib_execute(KUBECTL_CMD, DELETE_CMD, "sc", sc_name)
  File "/kadalu/kadalulib.py", line 156, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  Error from server (NotFound): storageclasses.storage.k8s.io "kadalu.kadalu-storage-ext-0" not found
[2021-12-08 07:59:10,877] INFO [kadalulib - 405:monitor_proc] - Restarted Process	 name=operator
[2021-12-08 07:59:11,490] INFO [main - 936:deploy_config_map] - Found existing configmap. Updating	 name=kadalu-info
[2021-12-08 07:59:11,498] INFO [main - 958:deploy_config_map] - ConfigMap Deployed	 manifest=/kadalu/templates/configmap.yaml uid=a7f5409e-59df-475d-b1e8-83b11993ad1a upgrade=True
[2021-12-08 07:59:12,262] INFO [main - 924:deploy_csi_pods] - Deployed CSI Pods	 manifest=/kadalu/templates/csi.yaml
[2021-12-08 07:59:12,263] INFO [main - 1008:main] - Upgrading to 	 version=0.8.8
[2021-12-08 07:59:12,269] INFO [main - 277:upgrade_storage_pods] - config map	 volname=kadalu-storage-ext-0 data={'volname': 'kadalu-storage-ext-0', 'volume_id': 'a5df2aa8-57e9-11ec-94cd-6202285304bd', 'type': 'External', 'pvReclaimPolicy': 'delete', 'kadalu_format': 'native', 'gluster_hosts': '192.168.2.4', 'gluster_volname': 'main', 'gluster_options': ''}
[2021-12-08 07:59:12,269] INFO [main - 277:upgrade_storage_pods] - config map	 volname=kadalu-storage-ext data={'volname': 'kadalu-storage-ext', 'volume_id': 'c908ed54-57e7-11ec-86bf-5e5448fb2947', 'type': 'External', 'pvReclaimPolicy': 'delete', 'kadalu_format': 'native', 'gluster_hosts': '192.168.2.4', 'gluster_volname': 'main', 'gluster_options': ''}

$ k get kds,sc
NAME                                                         AGE
kadalustorage.kadalu-operator.storage/kadalu-storage-ext-0   3m8s
$ k get sc
No resources found
```
>* less than a minute is very less time to confirm all internal knobs are turned correctly or not 😅
This is just logs from my cli and since then nothing has changed :)

**Comment by leelavg** [comment]
- What are the contents of `kadalu-storage-ext-gfs-delete.yaml`?
- There seems to be some issues in the way you are reusing external gluster 😅

**Comment by scr1ble** [comment]
>What are the contents of kadalu-storage-ext-gfs-delete.yaml?
```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: kadalu-storage-ext-0
spec:
  type: External
  # Omitting 'kadalu_format' or using 'native' as a value will create
  # 1 PV : 1 Subdir in external gluster volume
  kadalu_format: native
  details:
    # gluster_hosts: [ gluster1.kadalu.io, gluster2.kadalu.io ]
    gluster_host: 192.168.2.4
    gluster_volname: main
    # gluster_options: log-level=DEBUG
```
> There seems to be some issues in the way you are reusing external gluster 😅

I guess so, but absolutely can't understand what's wrong :(

**Comment by leelavg** [comment]
- uh oh, if you have cleaned it up before installing afresh why does below say two entries in config map 🤔 
```
[2021-12-08 07:59:12,269] INFO [main - 277:upgrade_storage_pods] - config map	 volname=kadalu-storage-ext-0 data={'volname': 'kadalu-storage-ext-0', 'volume_id': 'a5df2aa8-57e9-11ec-94cd-6202285304bd', 'type': 'External', 'pvReclaimPolicy': 'delete', 'kadalu_format': 'native', 'gluster_hosts': '192.168.2.4', 'gluster_volname': 'main', 'gluster_options': ''}
[2021-12-08 07:59:12,269] INFO [main - 277:upgrade_storage_pods] - config map	 volname=kadalu-storage-ext data={'volname': 'kadalu-storage-ext', 'volume_id': 'c908ed54-57e7-11ec-86bf-5e5448fb2947', 'type': 'External', 'pvReclaimPolicy': 'delete', 'kadalu_format': 'native', 'gluster_hosts': '192.168.2.4', 'gluster_volname': 'main', 'gluster_options': ''}
```

- I think I understood the issue, if you want to have a working setup, run the cleanup script, delete the empty directories from external bricks and then deploy kadalu
- I'm sure that'll work, in case if something goes wrong I may need to have my hands on the setup or reproducer steps to debug

**Comment by scr1ble** [comment]
It works! So is it only way to fix this? I mean ,in my opinion it's nota good  idea to cleanup kaDalu when it will be necessary.

**Comment by leelavg** [comment]
> So is it only way to fix this

- no! your initial report suggests that before re-using external gluster back-end bricks wasn't cleaned correctly
- it's work time for me, so while context switching b/n kadalu and my work I might've not provided clear instructions
- to be frank, reports in some of the comments are confusing and took time in creating a usable setup

---

- if cleanup is done for re-using same bricks correctly, then there'll no issue
- there's a k8s limitation that when you delete underlying storage pool and if there were any PVCs (irrespective of bound to apppod or not) using that pool, k8s reports that pool is deleted but kadalu refuses to do so
- above result would be a false positive and next set of issues will occur if above isn't fixed

**Comment by scr1ble** [comment]
I did a cleanup of the external `gluster` and removed all the` pv,pvc` before removing the `kds, sc`.
Ok. It's clean. Thanks a lot for your help again. I'm really appreciate it. Have a nice day and I'll close the issue.
