### ISSUE TITLE
MountVolume.NewMounter initialization failed (expected valid fsGroupPolicy, received nil value or empty string)

### ISSUE THREAD

**Issue by maxsivkov** [kadalu/kadalu#724]
Hello

*Environment:*
Kubernetes cluster v 1.18
kadalu:
```
kubectl kadalu version
kubectl-kadalu plugin: 0.8.8
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-6rdkj: 0.8.8
pod/kadalu-csi-nodeplugin-7wvkn: 0.8.8
pod/kadalu-csi-nodeplugin-f5mhm: 0.8.8
pod/kadalu-csi-nodeplugin-mqv9j: 0.8.8
pod/kadalu-csi-nodeplugin-qr2th: 0.8.8
pod/kadalu-csi-provisioner-0: 0.8.8
pod/operator-7d8cd5bcd-v7p5c: 0.8.8
pod/server-storage-pool-replica1-0-0: 0.8.8
pod/server-storage-pool-replica1-1-0: 0.8.8
pod/server-storage-pool-replica1-2-0: 0.8.8
```

Getting errors while running pod 
```
Events:
  Type     Reason                  Age                   From                     Message
  ----     ------                  ----                  ----                     -------
  Normal   SuccessfulAttachVolume  7m22s                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-461ae852-698f-4b2b-8f20-d4d4d44dabf5"
  Warning  FailedMount             3m3s                  kubelet                  Unable to attach or mount volumes: unmounted volumes=[gluster-vol1], unattached volumes=[default-token-k7w7v gluster-vol1]: timed out waiting for the condition
  Warning  FailedMount             62s (x11 over 7m14s)  kubelet                  MountVolume.NewMounter initialization failed for volume "pvc-461ae852-698f-4b2b-8f20-d4d4d44dabf5" : kubernetes.io/csi: expected valid fsGroupPolicy, received nil value or empty string
  Warning  FailedMount             48s (x2 over 5m19s)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[gluster-vol1], unattached volumes=[gluster-vol1 default-token-k7w7v]: timed out waiting for the condition
```

I successfully attached storage to the cluster using command
`kubectl kadalu storage-add storage-pool-replica1 --type Replica1 --pv-reclaim-policy delete --device worker-04:/dev/disk/gd0 --device worker-13:/dev/disk/gd0 --device worker-14:/dev/disk/gd0 --script-mode`

devices `/dev/disk/gd0`  are available on each node (wiped and created xfs filesystem)

storage class `kadalu.storage-pool-replica1` was created after `storage-pool-replica1` creation
I was able to create pvc:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-claim-kadalu-replica1
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: kadalu.storage-pool-replica1
  resources:
     requests:
       storage: 1Gi
```

The only errors I found came from `server-storage-pool-replica1-1-0` pod:

```log
INFO:     10.244.2.18:51666 - "GET /_api/metrics HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/kadalu/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/kadalu/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/kadalu/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/kadalu/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/kadalu/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/kadalu/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/kadalu/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/kadalu/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/kadalu/exporter.py", line 28, in metrics
    if os.path.exists(memory_usage_file_path):
NameError: name 'os' is not defined

```

I don't think the above stacktrace correspond to my issue. It corresponds to the ` /_api/metrics` endpoint...

**Comment by leelavg** [comment]
@maxsivkov 

- pardon the inconvenience, it's a regression in 0.8.8 fixed in #708 and will be part of next release

**Comment by maxsivkov** [comment]
> @maxsivkov
> 
> * pardon the inconvenience, it's a regression in 0.8.8 fixed in [Fix metrics issue & add exporter files under pylint #708](https://github.com/kadalu/kadalu/pull/708) and will be part of next release

Thanks for the quick reponse

Do you think #708 will also fix the `MountVolume.NewMounter initialization failed for volume "pvc-461ae852-698f-4b2b-8f20-d4d4d44dabf5" : kubernetes.io/csi: expected valid fsGroupPolicy, received nil value or empty string` error?

**Comment by leelavg** [comment]
> expected valid fsGroupPolicy, received nil value or empty string error?

- Ah, missed this detail 😅
- Nope, I don't think it's related and is a different issue 
- Might feel wrong to ask again, are you sure that you are on k8s 1.18?
- `kubelet` is throwing that error however `fsGroupPolicy` is in alpha on v1.19 🤔
- I cross checked side car versions however everything checks out
- Currently on mobile so couldn't help more right now 

Ask:
1. Pls reconfirm your k8s version 
2. Corresponding nodeplugin logs when you see above error
3. Your observations on storage classes is correct, did you use kadalu before or is this an upgrade?

**Comment by maxsivkov** [comment]
@leelavg , you're right!
1.
We have test cluster with nodes running v1.18.12 (workers and master) and v1.22.4 (2 workers only)
kadalu deployed on 1 node v1.18.12 and on 2 nodes v1.22.4

by default pod was scheduled on a v1.22.4 node.
After deploying pod to the 1.18.12 node it starts to work fine.


2.
*kadalu-csi-nodeplugin-f5mhm* ( this nodeplugin runs on a v1.22.4 node) has no errors during pod scheduling
`kubectl -n kadalu logs -f --tail=200 kadalu-csi-nodeplugin-f5mhm --all-containers`
output
```
<cut>
INFO:     10.244.2.18:39240 - "GET /_api/metrics HTTP/1.1" 200 OK
INFO:     10.244.2.18:40646 - "GET /_api/metrics HTTP/1.1" 200 OK
INFO:     10.244.2.18:42042 - "GET /_api/metrics HTTP/1.1" 200 OK
INFO:     10.244.2.18:43456 - "GET /_api/metrics HTTP/1.1" 200 OK
INFO:     10.244.2.18:44864 - "GET /_api/metrics HTTP/1.1" 200 OK
I1207 12:51:47.251826       1 main.go:112] Version: v2.0.1-0-g1aaa13a-dirty
I1207 12:51:47.251884       1 main.go:122] Attempting to open a gRPC connection with: "/plugin/csi.sock"
I1207 12:51:47.251907       1 connection.go:151] Connecting to unix:///plugin/csi.sock
I1207 12:51:55.235331       1 main.go:129] Calling CSI driver to discover driver name
I1207 12:51:55.235663       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I1207 12:51:55.235834       1 connection.go:181] GRPC request: {}
I1207 12:51:55.274248       1 connection.go:183] GRPC response: {"name":"kadalu","vendor_version":"0.8.8"}
I1207 12:51:55.274993       1 connection.go:184] GRPC error: <nil>
I1207 12:51:55.275553       1 main.go:139] CSI driver name: "kadalu"
I1207 12:51:55.275674       1 node_register.go:55] Starting Registration Server at: /registration/kadalu-reg.sock
I1207 12:51:55.276100       1 node_register.go:64] Registration Server started at: /registration/kadalu-reg.sock
I1207 12:51:55.276466       1 node_register.go:86] Skipping healthz server because port set to: 0
I1207 12:51:55.527364       1 main.go:79] Received GetInfo call: &InfoRequest{}
I1207 12:51:55.571751       1 main.go:89] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}



INFO:     10.244.2.18:46284 - "GET /_api/metrics HTTP/1.1" 200 OK
^C

```

Currently I have errors in `kadalu-csi-provisioner-0` pod, but these errors are unrelated to the fsGroupPolicy error:
```
[2021-12-07 16:06:09.368984 +0000] W [dict.c:1573:dict_get_with_ref] (-->/opt/lib/glusterfs/2021.11.12/xlator/performance/md-cache.so(+0xd7cc) [0x7f33c876e7cc] -->/opt/lib/libglusterfs.so.0(dict_get_iatt+0x30) [0x7f33cce74a00] -->/opt/lib/libglusterfs.so.0(dict_get_with_ref+0xdb) [0x7f33cce71e6b] ) 0-dict: dict OR key (virt-gf-prestat) is NULL [Invalid argument]
[2021-12-07 16:06:09.374104 +0000] W [dict.c:1573:dict_get_with_ref] (-->/opt/lib/glusterfs/2021.11.12/xlator/performance/md-cache.so(+0xd7cc) [0x7f33c876e7cc] -->/opt/lib/libglusterfs.so.0(dict_get_iatt+0x30) [0x7f33cce74a00] -->/opt/lib/libglusterfs.so.0(dict_get_with_ref+0xdb) [0x7f33cce71e6b] ) 0-dict: dict OR key (virt-gf-prestat) is NULL [Invalid argument]

```

**Comment by leelavg** [comment]
- Great, you are all good
- There were three revisions to CSIDriver resource from pre 1.44 to current 1.22
- Kadalu Operator might have picked up master version and deployed CSIDriver to be compatible with that version 
- No fix for that is needed, after cluster upgrade reaches a consistent state just restart the operator
- As mentioned earlier other fix will land in next version

**Comment by leelavg** [comment]
- Read your response too fast 😅, so it's a test cluster and you can schedule on 1.18 nodes only
- When you do your testing you can upgrade and restart operator

**Comment by maxsivkov** [comment]
@leelavg 

Thanks for your sup[port.

As far as we cannot have multiple CSIDriver CRDs in one cluster, I think I have two options:
* Move whole cluster to 1.22
* Revert 1.22 nodes to 1.18

Give me some time to decide)

**Comment by maxsivkov** [comment]
@leelavg 

I reverted kubelet  on 2 nodes from version 1.22 to 1.18, everything works fine now!
I'll close this issue.
