### ISSUE TITLE
Cannot update kaDalu because changed immutable parameter on CSIDriver resource

### ISSUE THREAD

**Issue by marcusaram** [kadalu/kadalu#735]
Operator is in loop with this error:

2022-01-04 18:46:37,249] INFO [main - 958:deploy_config_map] - ConfigMap Deployed	 manifest=/kadalu/templates/configmap.yaml uid=274bff60-41f8-4dba-aa51-268a6bb7e1a4 upgrade=True
Traceback (most recent call last):
  File "/kadalu/main.py", line 1029, in <module>
    main()
  File "/kadalu/main.py", line 1005, in main
    deploy_csi_pods(core_v1_client)
  File "/kadalu/main.py", line 904, in deploy_csi_pods
    lib_execute(KUBECTL_CMD, APPLY_CMD, "-f", filename)
  File "/kadalu/kadalulib.py", line 156, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  The CSIDriver "kadalu" is invalid: spec.podInfoOnMount: Invalid value: true: field is immutable
[2022-01-04 18:46:38,449] INFO [kadalulib - 405:monitor_proc] - Restarted Process	 name=operator
[2022-01-04 18:46:39,176] INFO [main - 936:deploy_config_map] - Found existing configmap. Updating	 name=kadalu-info
[2022-01-04 18:46:39,201] INFO [main - 958:deploy_config_map] - ConfigMap Deployed	 manifest=/kadalu/templates/configmap.yaml uid=274bff60-41f8-4dba-aa51-268a6bb7e1a4 upgrade=True

I'm not sure if I can delete CSIDriver object without losing all my PVC's. The field podInfoOnMount is immutable.

Running kaDalu 0.8.9 but same issue with 0.8.7 or 0.8.8

**Comment by leelavg** [comment]
@marcusaram thanks for the report and pardon the inconvenience 

1. Root cause will most probably is, upgraded kubernetes, not going into details, comment here if you want more info on how `CSIDriver` resource works
2. Yes, you can delete that right away and at the same time make sure that there will be no new pvc requests during deletion and creation of this resource

@vatsa287 can you take this up please?

- Fix is to delete existing CSIDriver resource and fail quietly, the issue is hit as we are trying to update this resource as part of upgrade  however most of the fields are immutable.
- And also set `attachRequired` to `false`
- Btw, improvise above stated fix as well (think of comparing resource version before deletion..)

**Comment by vatsa287** [comment]
Sure I'll look into it.

**Comment by marcusaram** [comment]
@leelavg Indeed it is upgraded Kubernetes (OKD), the v1beta1 storage api was replaced by v1 and thus de CSIDriver object is moved to the new storage v1 API.

**Comment by leelavg** [comment]
@marcusaram ack, I hope removing the existing resource fixed the issue.

**Comment by marcusaram** [comment]
@leelavg Sorry for the late reaction, since this cluster is running production I had to take some measures if it went wrong for some reasons. I had already patched the template in the operator container. Downscaled the operator, removed the CSIDriver and upscaled the operator. All went well and now I've the correct version.
