### ISSUE TITLE
UnboundLocalError: local variable 'response' referenced before assignment in exporter.py

### ISSUE THREAD

**Issue by fastlorenzo** [kadalu/kadalu#766]
The following block should be placed within the previous try/except otherwise `response` doesn't exist if an issue occurs:

https://github.com/kadalu/kadalu/blob/24a634a62949b4e3768cb05e51f209186ac39147/operator/exporter.py#L282-L290

Stack trace:
```yaml
operator-79647d85d-rk82d kadalu-operator [2022-02-20 13:08:16,802] ERROR [exporter - 276:collect_all_metrics] - Unable to reach the pod, displaying only default values  pod_name=kadalu-csi-nodeplugin-dg98w error=HTTPConnectionPool(host='10.42.3.135', port=8050): Read timed out. (read timeout=1)
operator-79647d85d-rk82d kadalu-operator INFO:     10.42.1.21:33614 - "GET /metrics HTTP/1.1" 500 Internal Server Error
operator-79647d85d-rk82d kadalu-operator ERROR:    Exception in ASGI application
operator-79647d85d-rk82d kadalu-operator Traceback (most recent call last):
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
operator-79647d85d-rk82d kadalu-operator     result = await app(self.scope, self.receive, self.send)
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
operator-79647d85d-rk82d kadalu-operator     return await self.app(scope, receive, send)
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
operator-79647d85d-rk82d kadalu-operator     await super().__call__(scope, receive, send)
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
operator-79647d85d-rk82d kadalu-operator     await self.middleware_stack(scope, receive, send)
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
operator-79647d85d-rk82d kadalu-operator     raise exc from None
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
operator-79647d85d-rk82d kadalu-operator     await self.app(scope, receive, _send)
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
operator-79647d85d-rk82d kadalu-operator     response = await self.dispatch_func(request, self.call_next)
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/exporter.py", line 381, in collect_metrics
operator-79647d85d-rk82d kadalu-operator     collect_and_set_prometheus_metrics()
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/exporter.py", line 298, in collect_and_set_prometheus_metrics
operator-79647d85d-rk82d kadalu-operator     metrics = collect_all_metrics()
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/exporter.py", line 282, in collect_all_metrics
operator-79647d85d-rk82d kadalu-operator     if response.status_code == 200:
operator-79647d85d-rk82d kadalu-operator UnboundLocalError: local variable 'response' referenced before assignment
operator-79647d85d-rk82d kadalu-operator [2022-02-20 13:08:16,807] ERROR [httptools_impl - 378:run_asgi] - Exception in ASGI application
operator-79647d85d-rk82d kadalu-operator Traceback (most recent call last):
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
operator-79647d85d-rk82d kadalu-operator     result = await app(self.scope, self.receive, self.send)
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
operator-79647d85d-rk82d kadalu-operator     return await self.app(scope, receive, send)
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
operator-79647d85d-rk82d kadalu-operator     await super().__call__(scope, receive, send)
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
operator-79647d85d-rk82d kadalu-operator     await self.middleware_stack(scope, receive, send)
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
operator-79647d85d-rk82d kadalu-operator     raise exc from None
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
operator-79647d85d-rk82d kadalu-operator     await self.app(scope, receive, _send)
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
operator-79647d85d-rk82d kadalu-operator     response = await self.dispatch_func(request, self.call_next)
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/exporter.py", line 381, in collect_metrics
operator-79647d85d-rk82d kadalu-operator     collect_and_set_prometheus_metrics()
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/exporter.py", line 298, in collect_and_set_prometheus_metrics
operator-79647d85d-rk82d kadalu-operator     metrics = collect_all_metrics()
operator-79647d85d-rk82d kadalu-operator   File "/kadalu/exporter.py", line 282, in collect_all_metrics
operator-79647d85d-rk82d kadalu-operator     if response.status_code == 200:
operator-79647d85d-rk82d kadalu-operator UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by leelavg** [comment]
Ref #767
