### ISSUE TITLE
[Bug]: Error showing kubectl-kadalu version

### ISSUE THREAD

**Issue by leenooks** [kadalu/kadalu#824]
**Describe the bug**
Not sure if you are aware, I'm using microk8s (which I believe it is supported), but `kubectl kadlue version` yields an error:

```
[root@a-1-1 ~]# kubectl kadalu version
kubectl-kadalu plugin: 0.8.14
Traceback (most recent call last):
  File "/snap/microk8s/3272/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/snap/microk8s/3272/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/kubectl-kadalu/__main__.py", line 117, in <module>
  File "/usr/bin/kubectl-kadalu/__main__.py", line 103, in main
  File "/usr/bin/kubectl-kadalu/__main__.py", line 85, in show_version
  File "/usr/bin/kubectl-kadalu/__main__.py", line 48, in get_all_kadalu_pods
  File "/usr/bin/kubectl-kadalu/utils.py", line 35, in execute
  File "/snap/microk8s/3272/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/snap/microk8s/3272/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'kubectl': 'kubectl'
``` 

If I create a softlink of `kubectl` to `microk8s.kubectl`, then it's a different error:
```
[root@a-1-1 ~]# kubectl kadalu version
kubectl-kadalu plugin: 0.8.14
Error while running the following command
$ kubectl get pods -nkadalu -oname

error: unknown flag `n'
```

But running `kubectl get pods -nkadalu -oname` works successfully:
```
[root@a-1-1 ~]# kubectl get pods -nkadalu -oname
pod/operator-765ff99d89-hfr9v
pod/kadalu-csi-nodeplugin-fq6xp
pod/kadalu-csi-nodeplugin-q5pdq
pod/kadalu-csi-nodeplugin-jbps4
pod/kadalu-csi-provisioner-0
pod/server-gfs-ec-0-0
pod/server-gfs-ec-2-0
pod/server-gfs-ec-1-0
```

**Comment by leelavg** [comment]
> which I believe it is supported
- in the sense we use `/var/snap/microk8s/common/var/lib/kubelet` as `kubelet` path if you deploy correct manifest for your distro

- `kubectl` not found, the cli tool expects `kubectl` is in `$PATH`
- After creating symlink it should've worked, maybe due to Python Subprocess the command didn't work as expected 🤔

@aravindavk any quick deductions?

**Comment by leenooks** [comment]
Yup, I have the same kubelet path:
```
[root@a-1-1 ~]# ls -ald /var/snap/microk8s/common/var/lib/kubelet
drwxr-x--- 1 root root 182 May 17 10:27 /var/snap/microk8s/common/var/lib/kubelet
```

I guess the difference is with microk8s there isnt a `kubectl` command (i have it as an alias to `microk8s kubectl`) - its also available as `microk8s.kubectl` (which is what my softlink pointed to when debugging this).
