### ISSUE TITLE
[Bug]: Pods stuck due to kadalu csi

### ISSUE THREAD

**Issue by MatteoManzoni** [kadalu/kadalu#948]
**Describe the bug**
Investigating some pods stuck in terminating I saw the following error in kadalu-csi-nodeplugin pod, kadalu-nodeplugin container:
```
[2022-12-28 16:28:02,045] ERROR [_server - 453:_call_behavior] - Exception calling application: [1]  
Traceback (most recent call last):
  File "/kadalu/lib/python3.10/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/nodeserver.py", line 154, in NodeUnpublishVolume
    unmount_volume(request.target_path)
  File "/kadalu/volumeutils.py", line 908, in unmount_volume
    device, _, _ = execute(*cmd)
  File "/kadalu/kadalulib.py", line 157, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]
```

Adding a log line at line 908 in `/kadalu/volumeutils.py` I see how the findmnt is failing as the searched path is not existing

I'm on kubernetes 1.26 and kadalu 1.0.0, the kadalu mode used is external gluster

**To Reproduce**
1. create a pod w/ mounted kadalu-backed pv
2. delete the pod
3. error will start appearing and the pod will get stuck in terminating

**Expected behavior**
Pods don't get stuck and kadalu doesn't try to findmnt non existings paths 

**Actual behavior**
Pods get stuck and the findmnt log is shown

**Environment:**
 - Kadalu Version: 1.0.0
 - K8S_DIST: kubernetes
 - External Gluster
 - Kuberneters version: 1.26

**Comment by vatsa287** [comment]
Thanks for reporting the issue @MatteoManzoni. Will look into this.

**Comment by cr0c0dylus** [comment]
I have the same error with nomad. It doesn't affect tasks, but errors in the log are not good.

[2023-03-16 14:23:09,761] ERROR [_server - 453:_call_behavior] - Exception calling application: [1]  
Traceback (most recent call last):
  File "/kadalu/lib/python3.10/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/nodeserver.py", line 154, in NodeUnpublishVolume
    unmount_volume(request.target_path)
  File "/kadalu/volumeutils.py", line 908, in unmount_volume
    device, _, _ = execute(*cmd)
  File "/kadalu/kadalulib.py", line 157, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]

**Comment by leelavg** [comment]
- I spent a good amount of time on this and at the same time, unable to reproduce it.

> mounted kadalu-backed pv
- is it `volumeMount: Block` in PVC or `pv_type: Block` in Storage Class?

**Comment by MatteoManzoni** [comment]
Hi @leelavg thank you so much for reaching back!
No sign of `volumeMount: Block` on the PVCs, as spec attached:
```
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: pvc-c77706eb-b549-4448-951c-55b8d368e964
  storageClassName: kadalu.kadalu
  volumeMode: Filesystem
```

Btw, I'm seeing the following log as repored by @cr0c0dylus too:
```
[2023-04-24 16:16:28,121] ERROR [_server - 453:_call_behavior] - Exception calling application: [1]  
Traceback (most recent call last):
  File "/kadalu/lib/python3.10/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/nodeserver.py", line 154, in NodeUnpublishVolume
    unmount_volume(request.target_path)
  File "/kadalu/volumeutils.py", line 908, in unmount_volume
    device, _, _ = execute(*cmd)
  File "/kadalu/kadalulib.py", line 157, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]
```

Can it be related to the issue we are facing?

**Comment by leelavg** [comment]
It's a bit confusing to me, for `volumeMode: Filesystem` exception mentioned will not be hit as per   codepath and moreover I didn't face this even after trying many scenarios.

Nevertheless, will re-try once again.

**Comment by leelavg** [comment]
- I gave another try, still not able to hit this.
- I'm on
```
# k version --short 
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.26.4+k3s1
```
- Nodeplugin unpublish worked perfectly
```
[2023-06-22 03:56:44,770] DEBUG [nodeserver - 141:NodeUnpublishVolume] - Received the unmount request  volume=pvc-d9822c2c-9544-4b13-af73-c934f68a98c5
```

@MatteoManzoni, @RadoslawBuller, @cr0c0dylus pls provide me any pointers that I'll be able to hit it?

**Comment by RadoslawBuller** [comment]
@leelavg 

It keeps throwing all the time:

[2023-07-23 15:14:19,313] ERROR [_server - 454:_call_behavior] - Exception calling application: [1]
Traceback (most recent call last):
  File "/kadalu/lib/python3.10/site-packages/grpc/_server.py", line 444, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/nodeserver.py", line 145, in NodeUnpublishVolume
    unmount_volume(request.target_path)
  File "/kadalu/volumeutils.py", line 901, in unmount_volume
    device, _, _ = execute(*cmd)
  File "/kadalu/kadalulib.py", line 187, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]

this is on:
**# kc version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.2**

**Comment by leelavg** [comment]
Ack, I'll see if I can get a real k8s cluster rather than my local k3d and re-look again.

If only I could find the root cause the fix will mostly be straightforward.

**Comment by RadoslawBuller** [comment]
Just to add that it's simple 3 node K8s cluster with 9 PVs where kadalu was installed from scratch.
Also, from the very beginning all PVs went into not healthy state needing healing but of course stays in heal pending state (replica3). Not sure if it's related.
If you need any analysis dumps on my side that could help you, just shoot.

Cheers
Radek

**Comment by leelavg** [comment]
oohk, found it now, will fix it after some more confirmation.
