### ISSUE TITLE
[Bug]: Not able to connect to api-server 10.96.0.1 from kadalu operator

### ISSUE THREAD

**Issue by Kanaga13579** [kadalu/kadalu#975]
**Describe the bug**
Not able to connect to api-server 10.96.0.1 from kadalu operator
**To Reproduce**
1. Deploy kadalu operator using helm charts in kadalu namespace

**Expected behavior**
pv should be provisioned

**Actual behavior**
A clear and concise description of what actually happened.
kadalu operator not able to connect to 10.96.0.1:443
[2023-03-29 11:32:02,792] WARNING [connectionpool - 812:urlopen] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8dc02fbdc0>, 'Connection to 10.96.0.1 timed out. (connect timeout=None)')': /version/
Traceback (most recent call last):
File "/kadalu/main.py", line 1043, in <module>
main()
File "/kadalu/main.py", line 1019, in main
deploy_csi_pods(core_v1_client)
File "/kadalu/main.py", line 913, in deploy_csi_pods
lib_execute(KUBECTL_CMD, APPLY_CMD, "-f", filename)
File "/kadalu/kadalulib.py", line 157, in execute
raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1] Unable to connect to the server: dial tcp 10.96.0.1:443: i/o timeout

**Environment:**

 - Kadalu Version: 1.0.0
 - K8S_DIST: kubernetes

**Screenshots or Logs**
If applicable, add any screenshots to help explain your problem. Try capturing relevant logs, post them to http://gist.github.com/ and post the links in the issue.
![image](https://user-images.githubusercontent.com/10193577/228552478-65f5ec99-7b0a-4de8-bd6a-d9e191349966.png)

**Additional context**

**Comment by Kanaga13579** [comment]
After updating calico latest version 3.25.1, this issue got fixed.
